using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using AsterERP.Workflow.Core.Cmd;
using AsterERP.Workflow.Core.Event;
using AsterERP.Workflow.Core.Variable;

namespace AsterERP.Workflow.Core.Services;

public interface ITaskService
{
    Task<TaskImplementation?> GetTaskAsync(string taskId, CancellationToken cancellationToken = default);
    Task<TaskImplementation> CreateTaskAsync(TaskImplementation task, CancellationToken cancellationToken = default);
    Task<TaskImplementation> SaveTaskAsync(TaskImplementation task, CancellationToken cancellationToken = default);
    Task DeleteTaskAsync(string taskId, string? deleteReason = null, bool cascade = false, CancellationToken cancellationToken = default);
    Task DeleteTasksAsync(ICollection<string> taskIds, string? deleteReason = null, bool cascade = false, CancellationToken cancellationToken = default);
    Task CompleteTaskAsync(string taskId, Dictionary<string, object?>? variables = null, CancellationToken cancellationToken = default);
    Task CompleteTaskAsync(string taskId, Dictionary<string, object?>? variables, Dictionary<string, object?>? transientVariables, CancellationToken cancellationToken = default);
    Task DelegateTaskAsync(string taskId, string userId, CancellationToken cancellationToken = default);
    Task ResolveTaskAsync(string taskId, Dictionary<string, object?>? variables = null, CancellationToken cancellationToken = default);
    Task ResolveTaskAsync(string taskId, Dictionary<string, object?>? variables, Dictionary<string, object?>? transientVariables, CancellationToken cancellationToken = default);
    Task SetAssigneeAsync(string taskId, string userId, CancellationToken cancellationToken = default);
    Task SetOwnerAsync(string taskId, string userId, CancellationToken cancellationToken = default);
    Task ClaimTaskAsync(string taskId, string userId, CancellationToken cancellationToken = default);
    Task UnclaimTaskAsync(string taskId, CancellationToken cancellationToken = default);
    Task SetPriorityAsync(string taskId, int priority, CancellationToken cancellationToken = default);
    Task SetDueDateAsync(string taskId, DateTime? dueDate, CancellationToken cancellationToken = default);
    Task<List<TaskImplementation>> GetTasksAsync(CancellationToken cancellationToken = default);
    Task<List<TaskImplementation>> GetTasksAssignedToUserAsync(string userId, CancellationToken cancellationToken = default);
    Task<List<TaskImplementation>> GetTasksByProcessInstanceIdAsync(string processInstanceId, CancellationToken cancellationToken = default);
    Task<object?> GetVariableAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task<T?> GetVariableAsync<T>(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task<object?> GetVariableLocalAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task<Dictionary<string, object?>> GetVariablesAsync(string taskId, ICollection<string>? variableNames = null, CancellationToken cancellationToken = default);
    Task<Dictionary<string, object?>> GetVariablesLocalAsync(string taskId, ICollection<string>? variableNames = null, CancellationToken cancellationToken = default);
    Task<VariableInstanceEntity?> GetVariableInstanceAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task<VariableInstanceEntity?> GetVariableInstanceLocalAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task<Dictionary<string, VariableInstanceEntity>> GetVariableInstancesAsync(string taskId, ICollection<string>? variableNames = null, CancellationToken cancellationToken = default);
    Task<Dictionary<string, VariableInstanceEntity>> GetVariableInstancesLocalAsync(string taskId, ICollection<string>? variableNames = null, CancellationToken cancellationToken = default);
    Task<bool> HasVariableAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task<bool> HasVariableLocalAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task SetVariableAsync(string taskId, string variableName, object? value, CancellationToken cancellationToken = default);
    Task SetVariableLocalAsync(string taskId, string variableName, object? value, CancellationToken cancellationToken = default);
    Task SetVariablesAsync(string taskId, Dictionary<string, object?> variables, CancellationToken cancellationToken = default);
    Task SetVariablesLocalAsync(string taskId, Dictionary<string, object?> variables, CancellationToken cancellationToken = default);
    Task RemoveVariableAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task RemoveVariableLocalAsync(string taskId, string variableName, CancellationToken cancellationToken = default);
    Task RemoveVariablesAsync(string taskId, ICollection<string> variableNames, CancellationToken cancellationToken = default);
    Task RemoveVariablesLocalAsync(string taskId, ICollection<string> variableNames, CancellationToken cancellationToken = default);
    Task<CommentEntity> AddCommentAsync(string taskId, string? processInstanceId, string message, CancellationToken cancellationToken = default);
    Task<CommentEntity> AddCommentAsync(string taskId, string? processInstanceId, string? type, string message, CancellationToken cancellationToken = default);
    Task<CommentEntity?> GetCommentAsync(string commentId, CancellationToken cancellationToken = default);
    Task DeleteCommentAsync(string commentId, CancellationToken cancellationToken = default);
    Task<List<CommentEntity>> GetTaskCommentsAsync(string taskId, CancellationToken cancellationToken = default);
    Task<List<CommentEntity>> GetTaskCommentsAsync(string taskId, string type, CancellationToken cancellationToken = default);
    Task<List<CommentEntity>> GetCommentsByTypeAsync(string type, CancellationToken cancellationToken = default);
    Task<List<CommentEntity>> GetProcessInstanceCommentsAsync(string processInstanceId, string? type = null, CancellationToken cancellationToken = default);
    Task<List<EventEntity>> GetTaskEventsAsync(string taskId, CancellationToken cancellationToken = default);
    Task<EventEntity?> GetEventAsync(string eventId, CancellationToken cancellationToken = default);
    Task<AttachmentEntity> CreateAttachmentAsync(string? attachmentType, string? taskId, string? processInstanceId, string? attachmentName, string? attachmentDescription, byte[]? content, CancellationToken cancellationToken = default);
    Task<AttachmentEntity> CreateAttachmentAsync(string? attachmentType, string? taskId, string? processInstanceId, string? attachmentName, string? attachmentDescription, string? url, CancellationToken cancellationToken = default);
    Task<AttachmentEntity?> GetAttachmentAsync(string attachmentId, CancellationToken cancellationToken = default);
    Task<byte[]?> GetAttachmentContentAsync(string attachmentId, CancellationToken cancellationToken = default);
    Task<List<AttachmentEntity>> GetTaskAttachmentsAsync(string taskId, CancellationToken cancellationToken = default);
    Task<List<AttachmentEntity>> GetProcessInstanceAttachmentsAsync(string processInstanceId, CancellationToken cancellationToken = default);
    Task SaveAttachmentAsync(AttachmentEntity attachment, CancellationToken cancellationToken = default);
    Task DeleteAttachmentAsync(string attachmentId, CancellationToken cancellationToken = default);
    Task AddCandidateUserAsync(string taskId, string userId, CancellationToken cancellationToken = default);
    Task AddCandidateGroupAsync(string taskId, string groupId, CancellationToken cancellationToken = default);
    Task AddUserIdentityLinkAsync(string taskId, string userId, string identityLinkType, CancellationToken cancellationToken = default);
    Task AddGroupIdentityLinkAsync(string taskId, string groupId, string identityLinkType, CancellationToken cancellationToken = default);
    Task DeleteCandidateUserAsync(string taskId, string userId, CancellationToken cancellationToken = default);
    Task DeleteCandidateGroupAsync(string taskId, string groupId, CancellationToken cancellationToken = default);
    Task DeleteUserIdentityLinkAsync(string taskId, string userId, string identityLinkType, CancellationToken cancellationToken = default);
    Task DeleteGroupIdentityLinkAsync(string taskId, string groupId, string identityLinkType, CancellationToken cancellationToken = default);
    Task<List<IdentityLinkEntity>> GetIdentityLinksForTaskAsync(string taskId, CancellationToken cancellationToken = default);
    Task<List<TaskImplementation>> GetSubTasksAsync(string parentTaskId, CancellationToken cancellationToken = default);
    Task<Dictionary<string, DataObjectImpl>> GetDataObjectsAsync(string taskId, ICollection<string>? dataObjectNames = null, CancellationToken cancellationToken = default);
    Task<DataObjectImpl?> GetDataObjectAsync(string taskId, string dataObjectName, CancellationToken cancellationToken = default);
}
