import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import { archiveProjectManagementProject, createProjectManagementProject, deleteProjectManagementProject, getProjectManagementHomeProjects, getProjectManagementHomeSummary, updateProjectManagementProject } from '../../../api/project-management/projectManagement.api';
import type { ProjectManagementHomeHealth, ProjectManagementHomeProjectItem, ProjectManagementHomeQuery, ProjectManagementHomeSummaryResponse, ProjectManagementProjectUpsertRequest } from '../../../api/project-management/projectManagement.types';
import { isHttpError } from '../../../core/http/httpError';
import { formatMessage } from '../../../core/i18n/formatMessage';
import { useI18n } from '../../../core/i18n/I18nProvider';
import { projectManagementQueryKeys } from '../../../core/query/projectManagementQueryKeys';
import { useApiMutation } from '../../../core/query/useApiMutation';
import { useAuthStore } from '../../../core/state';
import { useConfirm } from '../../../shared/feedback/useConfirm';
import { useMessage } from '../../../shared/feedback/useMessage';
import { Page403 } from '../../../shared/status/Page403';
import { PmBox, PmButton, PmChip, PmDivider, PmFormInput, PmFormSelect, PmIcon, PmIconButton, PmMenuItem, PmPage, PmPane, PmPopover, PmRow, PmSkeletonRows, PmSurface, PmTab, PmTabs, PmText, PmTooltip, PmStack } from '../../../ui/project-management';
import { ProjectCreateDialog } from '../project-create/ProjectCreateDialog';
import { projectCenterPreferenceKey, readProjectCenterPreferences, rememberRecentProject, toggleProjectFavorite, writeProjectCenterPreferences, type ProjectCenterCollection, type ProjectCenterPreferences } from '../state/projectCenterPreferences';
import { useProjectManagementWorkspaceScope } from '../state/projectManagementWorkspaceScope';

import { useProjectHomeRealtime } from './useProjectHomeRealtime';

const healthLabels: Record<string, string> = { Completed: 'projectManagement.home.health.Completed', UpdateMissing: 'projectManagement.home.health.UpdateMissing', AtRisk: 'projectManagement.home.health.AtRisk', OffTrack: 'projectManagement.home.health.OffTrack', OnTrack: 'projectManagement.home.health.OnTrack', NoUpdateExpected: 'projectManagement.home.health.NoUpdateExpected' };
const statusLabels: Record<string, string> = { Planning: 'projectManagement.home.status.Planning', Active: 'projectManagement.home.status.Active', Paused: 'projectManagement.home.status.Paused', Completed: 'projectManagement.home.status.Completed', Canceled: 'projectManagement.home.status.Canceled', Archived: 'projectManagement.home.status.Archived' };
const priorityLabels: Record<string, string> = { Low: 'projectManagement.home.priority.Low', Medium: 'projectManagement.home.priority.Medium', High: 'projectManagement.home.priority.High', Urgent: 'projectManagement.home.priority.Urgent' };
const emptyForm: ProjectManagementProjectUpsertRequest = { projectCode: '', projectName: '', status: 'Planning', priority: 'Medium', progressPercent: 0, versionNo: 0 };

export function ProjectHomeShell() {
  const scope = useProjectManagementWorkspaceScope();
  const userId = useAuthStore(state => state.user?.userId ?? '');
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { translate } = useI18n();
  const confirm = useConfirm();
  const message = useMessage();
  const [insightsOpen, setInsightsOpen] = useState(() => localStorage.getItem('pm-home-insights') !== 'false');
  const [filterAnchor, setFilterAnchor] = useState<HTMLElement | null>(null);
  const [insightTab, setInsightTab] = useState<'health' | 'leads'>('health');
  const [density, setDensity] = useState<'compact' | 'default' | 'comfortable'>(() => (localStorage.getItem('pm-home-density') as 'compact' | 'default' | 'comfortable') || 'default');
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<ProjectManagementHomeProjectItem | null>(null);
  const [form, setForm] = useState(emptyForm);
  const preferenceKey = projectCenterPreferenceKey(userId, scope.tenantId, scope.appCode);
  const [preferences, setPreferences] = useState<ProjectCenterPreferences>(() => readProjectCenterPreferences(preferenceKey));
  const focusIndex = useRef(0);
  const collection = (searchParams.get('collection') as ProjectCenterCollection | null) || 'all';
  const query = useMemo<ProjectManagementHomeQuery>(() => ({ collection, keyword: searchParams.get('keyword') || undefined, health: (searchParams.get('health') as ProjectManagementHomeHealth | null) || undefined, priority: searchParams.get('priority') || undefined, leadUserId: searchParams.get('leadUserId') || undefined, status: searchParams.get('status') || undefined, targetDateFrom: searchParams.get('targetDateFrom') || undefined, targetDateTo: searchParams.get('targetDateTo') || undefined, includeArchived: searchParams.get('includeArchived') === 'true', sortBy: searchParams.get('sortBy') || 'updated', sortDirection: (searchParams.get('sortDirection') as 'asc' | 'desc' | null) || 'desc', pageIndex: Number(searchParams.get('pageIndex') || 1), pageSize: 50 }), [collection, searchParams]);
  const projectsQuery = useQuery({ enabled: scope.isAvailable, queryKey: projectManagementQueryKeys.homeProjects(scope, query), queryFn: ({ signal }) => getProjectManagementHomeProjects(query, signal) });
  const summaryQuery = useQuery({ enabled: scope.isAvailable && insightsOpen, queryKey: projectManagementQueryKeys.homeSummary(scope, query), queryFn: ({ signal }) => getProjectManagementHomeSummary({ ...query, pageIndex: 1, pageSize: 50 }, signal) });
  const realtime = useProjectHomeRealtime('/hubs/system-notification', scope, scope.isAvailable);
  const rows = projectsQuery.data?.data.items ?? [];
  const visibleRows = collection === 'favorites' ? rows.filter(row => preferences.favoriteProjectIds.includes(row.id)) : collection === 'recent' ? [...rows].sort((a, b) => preferences.recentProjectIds.indexOf(a.id) - preferences.recentProjectIds.indexOf(b.id)) : rows;
  const refresh = useCallback(() => { void queryClient.invalidateQueries({ queryKey: projectManagementQueryKeys.homeProjectsRoot(scope) }); void queryClient.invalidateQueries({ queryKey: projectManagementQueryKeys.homeSummaryRoot(scope) }); }, [queryClient, scope]);
  const savePreference = useCallback((next: ProjectCenterPreferences) => { setPreferences(next); writeProjectCenterPreferences(preferenceKey, next); }, [preferenceKey]);
  const setParam = useCallback((name: string, value?: string) => { const next = new URLSearchParams(searchParams); if (value) next.set(name, value); else next.delete(name); setSearchParams(next); }, [searchParams, setSearchParams]);
  const closeDialog = () => { setDialogOpen(false); setEditing(null); setForm(emptyForm); };
  const saveMutation = useApiMutation({ mutationFn: (value: ProjectManagementProjectUpsertRequest) => editing ? updateProjectManagementProject(editing.id, value) : createProjectManagementProject(value), onError: error => message.error(isHttpError(error) && error.status === 409 ? translate('projectManagement.home.conflict') : translate('projectManagement.home.createFailed')), onSuccess: () => { message.success(editing ? translate('projectManagement.home.updateSuccess') : translate('projectManagement.home.createSuccess')); closeDialog(); refresh(); } });
  const archiveMutation = useApiMutation({ mutationFn: (row: ProjectManagementHomeProjectItem) => archiveProjectManagementProject(row.id, row.versionNo), onSuccess: refresh, onError: () => message.error(translate('projectManagement.home.archiveFailed')) });
  const deleteMutation = useApiMutation({ mutationFn: (row: ProjectManagementHomeProjectItem) => deleteProjectManagementProject(row.id, row.versionNo), onSuccess: refresh, onError: () => message.error(translate('projectManagement.home.deleteFailed')) });
  const openProject = (row: ProjectManagementHomeProjectItem) => { savePreference(rememberRecentProject(preferences, row.id)); navigate(`/platform/project-management/projects/${encodeURIComponent(row.id)}/overview`); };
  const openCreate = () => { setEditing(null); setForm(emptyForm); setDialogOpen(true); };
  const openEdit = (row: ProjectManagementHomeProjectItem) => { setEditing(row); setForm({ projectCode: row.projectCode, projectName: row.projectName, status: row.status, priority: row.priority, ownerUserId: row.ownerUserId, startDate: row.startDate, dueDate: row.targetDate, progressPercent: row.progressPercent, versionNo: row.versionNo }); setDialogOpen(true); };

  useEffect(() => setPreferences(readProjectCenterPreferences(preferenceKey)), [preferenceKey]);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement || event.target instanceof HTMLSelectElement) return; if (event.key === 'c') { event.preventDefault(); openCreate(); } if (event.key === 'ArrowDown') { focusIndex.current = Math.min(focusIndex.current + 1, Math.max(visibleRows.length - 1, 0)); document.querySelector<HTMLElement>(`[data-home-row="${focusIndex.current}"]`)?.focus(); } if (event.key === 'ArrowUp') { focusIndex.current = Math.max(focusIndex.current - 1, 0); document.querySelector<HTMLElement>(`[data-home-row="${focusIndex.current}"]`)?.focus(); } if (event.key === 'Enter') document.querySelector<HTMLElement>(`[data-home-row="${focusIndex.current}"]`)?.click(); }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, [visibleRows.length]);

  if (!scope.isAvailable) return <Page403 />;
  const noResults = !projectsQuery.isLoading && visibleRows.length === 0;
  const rowMinHeight = density === 'compact' ? 44 : density === 'comfortable' ? 60 : 52;
  return <PmPage>
    <PmPane sx={{ flex: 1, overflow: 'auto' }}><PmSurface>
      <PmBox sx={{ display: 'flex', alignItems: 'center', gap: 1, height: 40 }}><PmTooltip title={translate('projectManagement.home.back')}><PmIconButton aria-label={translate('projectManagement.home.back')} onClick={() => navigate(-1)}><PmIcon name="back" /></PmIconButton></PmTooltip><PmTooltip title={translate('projectManagement.home.forward')}><PmIconButton aria-label={translate('projectManagement.home.forward')} onClick={() => navigate(1)}><PmIcon name="forward" /></PmIconButton></PmTooltip><PmText fontSize=".8rem" fontWeight={650}>{translate('projectManagement.home.title')}</PmText><PmIconButton aria-label={translate('projectManagement.home.create')} onClick={openCreate}><PmIcon name="plus" /></PmIconButton></PmBox>
      <PmDivider />
      <PmBox sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', py: 2 }}><PmText variant="h1" fontSize="1.35rem" fontWeight={700}>{translate('projectManagement.home.title')}</PmText><PmButton onClick={openCreate} startIcon={<PmIcon name="plus" />} variant="contained">{translate('projectManagement.home.create')}</PmButton></PmBox>
      <PmBox sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 2, flexWrap: 'wrap' }}><PmTabs onChange={(_, value) => setParam('collection', String(value))} value={collection}><PmTab label={translate('projectManagement.home.allProjects')} value="all" /><PmTab label={translate('projectManagement.home.favorites')} value="favorites" /><PmTab label={translate('projectManagement.home.recent')} value="recent" /></PmTabs><PmBox sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}><PmFormInput aria-label={translate('projectManagement.home.search')} defaultValue={searchParams.get('keyword') || ''} onKeyDown={event => { if (event.key === 'Enter') setParam('keyword', (event.currentTarget as HTMLInputElement).value.trim() || undefined); }} placeholder={translate('projectManagement.home.search')} size="small" sx={{ width: 180 }} /><PmButton onClick={event => setFilterAnchor(event.currentTarget)} startIcon={<PmIcon name="filter" />}>{translate('projectManagement.home.filter')}</PmButton><PmFormSelect label={translate('projectManagement.home.density')} value={density} onChange={event => { const value = String(event.target.value) as typeof density; setDensity(value); localStorage.setItem('pm-home-density', value); }}><PmMenuItem value="compact">{translate('projectManagement.home.compact')}</PmMenuItem><PmMenuItem value="default">{translate('projectManagement.home.defaultDensity')}</PmMenuItem><PmMenuItem value="comfortable">{translate('projectManagement.home.comfortable')}</PmMenuItem></PmFormSelect><PmButton onClick={() => { const next = !insightsOpen; setInsightsOpen(next); localStorage.setItem('pm-home-insights', String(next)); }}>{translate('projectManagement.home.insights')}</PmButton></PmBox></PmBox>
      <PmPopover anchorEl={filterAnchor} anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }} onClose={() => setFilterAnchor(null)} open={Boolean(filterAnchor)}><PmBox sx={{ p: 2, display: 'grid', gap: 1.25, minWidth: 240 }}><PmFormSelect label={translate('projectManagement.home.allStatuses')} value={searchParams.get('status') || ''} onChange={event => setParam('status', String(event.target.value) || undefined)}><PmMenuItem value="">{translate('projectManagement.home.allStatuses')}</PmMenuItem>{Object.keys(statusLabels).map(value => <PmMenuItem key={value} value={value}>{translate(statusLabels[value])}</PmMenuItem>)}</PmFormSelect><PmFormSelect label={translate('projectManagement.home.allPriorities')} value={searchParams.get('priority') || ''} onChange={event => setParam('priority', String(event.target.value) || undefined)}><PmMenuItem value="">{translate('projectManagement.home.allPriorities')}</PmMenuItem>{Object.keys(priorityLabels).map(value => <PmMenuItem key={value} value={value}>{translate(priorityLabels[value])}</PmMenuItem>)}</PmFormSelect>{(searchParams.get('status') || searchParams.get('priority') || searchParams.get('health') || searchParams.get('keyword')) && <PmButton onClick={() => { setSearchParams({ collection }); setFilterAnchor(null); }}>{translate('projectManagement.home.clearFilters')}</PmButton>}</PmBox></PmPopover>
      {projectsQuery.isLoading ? <PmSkeletonRows count={8} /> : projectsQuery.isError ? <State title={translate('projectManagement.home.loadingFailed')} action={<PmButton onClick={() => void projectsQuery.refetch()}>{translate('projectManagement.home.retry')}</PmButton>} /> : noResults ? <State title={searchParams.toString() ? translate('projectManagement.home.noResults') : translate('projectManagement.home.empty')} action={<PmButton onClick={openCreate}>{translate('projectManagement.home.create')}</PmButton>} /> : <PmBox sx={{ minWidth: 760 }}><PmRow sx={{ gridTemplateColumns: 'minmax(240px, 1fr) 110px 90px 120px 120px 70px 90px', minHeight: 38, color: 'text.secondary', fontSize: '.7rem', borderBottom: 0 }}><span>{translate('projectManagement.home.name')}</span><span>{translate('projectManagement.home.health')}</span><span>{translate('projectManagement.home.priority')}</span><span>{translate('projectManagement.home.lead')}</span><span>{translate('projectManagement.home.targetDate')}</span><span>{translate('projectManagement.home.issues')}</span><span>{translate('projectManagement.home.status')}</span></PmRow>{visibleRows.map((row, index) => <ProjectRow densityHeight={rowMinHeight} key={row.id} row={row} index={index} onClick={() => openProject(row)} onEdit={() => openEdit(row)} onArchive={() => archiveMutation.mutate(row)} onDelete={() => confirm({ title: translate('projectManagement.home.deleteTitle'), content: formatMessage(translate('projectManagement.home.deleteDescription'), { name: row.projectName }), confirmText: translate('projectManagement.home.delete'), onConfirm: () => deleteMutation.mutate(row) })} onFavorite={() => savePreference(toggleProjectFavorite(preferences, row.id))} translate={translate} />)}</PmBox>}
    </PmSurface></PmPane>
    {insightsOpen && <Insights insightTab={insightTab} setInsightTab={setInsightTab} summaryQuery={summaryQuery} setParam={setParam} translate={translate} connectionState={realtime.connectionState} />}
    <ProjectCreateDialog editing={Boolean(editing)} initialValue={form} onClose={closeDialog} onSubmit={value => { setForm(value); saveMutation.mutate(value); }} open={dialogOpen} pending={saveMutation.isPending} />
  </PmPage>;
}

function ProjectRow({ row, index, densityHeight, onClick, onEdit, onArchive, onDelete, onFavorite, translate }: { row: ProjectManagementHomeProjectItem; index: number; densityHeight: number; onClick: () => void; onEdit: () => void; onArchive: () => void; onDelete: () => void; onFavorite: () => void; translate: (key: string) => string }) {
  return <PmRow data-home-row={index} onClick={onClick} onKeyDown={event => { if (event.key === 'Enter') onClick(); }} role="button" tabIndex={0} sx={{ gridTemplateColumns: 'minmax(240px, 1fr) 110px 90px 120px 120px 70px 90px', minHeight: densityHeight, fontSize: '.78rem', cursor: 'pointer', '&:hover .pm-row-actions': { opacity: 1 } }}><PmBox sx={{ display: 'flex', alignItems: 'center', gap: 1, minWidth: 0 }}><PmIcon name="folder" size={16} /><PmText noWrap fontSize="inherit" fontWeight={600}>{row.projectName}</PmText>{row.currentMilestoneName && <PmText noWrap color="text.secondary" fontSize=".7rem">{row.currentMilestoneName}</PmText>}</PmBox><PmBox sx={{ display: 'flex', gap: .5, alignItems: 'center' }}><PmBox sx={{ width: 7, height: 7, borderRadius: '50%', bgcolor: row.health === 'AtRisk' || row.health === 'OffTrack' ? 'error.main' : 'success.main' }} /><PmText fontSize="inherit">{translate(healthLabels[row.health] || row.health)}</PmText></PmBox><PmText fontSize="inherit">{translate(priorityLabels[row.priority] || row.priority)}</PmText><PmText noWrap fontSize="inherit">{row.ownerDisplayName || translate('projectManagement.home.unassigned')}</PmText><PmText fontSize="inherit">{row.targetDate ? new Date(row.targetDate).toLocaleDateString() : '—'}</PmText><PmText color="primary.main" fontSize="inherit">{row.openIssueCount}</PmText><PmChip label={translate(statusLabels[row.status] || row.status)} color={row.status === 'Completed' ? 'success' : row.status === 'Active' ? 'primary' : 'default'} /><PmBox className="pm-row-actions" sx={{ display: 'flex', gap: .25, position: 'absolute', right: 4, opacity: 0, bgcolor: 'background.paper' }} onClick={event => event.stopPropagation()}><PmIconButton aria-label={translate('projectManagement.home.favorite')} onClick={onFavorite} size="small"><PmIcon name="star" /></PmIconButton><PmIconButton aria-label={translate('projectManagement.home.edit')} onClick={onEdit} size="small"><PmIcon name="settings" /></PmIconButton><PmIconButton aria-label={translate('projectManagement.home.archive')} onClick={onArchive} size="small"><PmIcon name="archive" /></PmIconButton><PmIconButton aria-label={translate('projectManagement.home.delete')} onClick={onDelete} size="small"><PmIcon name="trash" /></PmIconButton></PmBox></PmRow>;
}

function Insights({ insightTab, setInsightTab, summaryQuery, setParam, translate, connectionState }: { insightTab: 'health' | 'leads'; setInsightTab: (value: 'health' | 'leads') => void; summaryQuery: { isError: boolean; data?: { data: ProjectManagementHomeSummaryResponse } }; setParam: (name: string, value?: string) => void; translate: (key: string) => string; connectionState: string }) {
  return <PmPane paneWidth={360} sx={{ borderLeft: 1, borderColor: 'divider', display: { xs: 'none', lg: 'block' } }}><PmSurface><PmTabs onChange={(_, value) => setInsightTab(String(value) as 'health' | 'leads')} value={insightTab}><PmTab label={translate('projectManagement.home.health')} value="health" /><PmTab label={translate('projectManagement.home.leads')} value="leads" /></PmTabs><PmDivider sx={{ mb: 2 }} />{summaryQuery.isError ? <State title={translate('projectManagement.home.loadingFailed')} /> : insightTab === 'health' ? summaryQuery.data?.data.health.map(item => <InsightRow key={item.key} label={translate(healthLabels[item.key] || item.key)} count={item.count} onClick={() => setParam('health', item.key)} />) : <>{summaryQuery.data?.data.leads.map(item => <InsightRow key={item.userId || 'unassigned'} label={item.displayName} count={item.count} onClick={item.userId ? () => setParam('leadUserId', item.userId) : undefined} />)}<InsightRow label={translate('projectManagement.home.unassigned')} count={summaryQuery.data?.data.unassignedCount ?? 0} /></>}{connectionState !== 'connected' && <PmText aria-live="polite" color="warning.main" fontSize=".72rem" sx={{ mt: 3 }}>{connectionState === 'reconnecting' ? translate('projectManagement.home.connection.reconnecting') : translate('projectManagement.home.connection.disconnected')}</PmText>}</PmSurface></PmPane>;
}

function InsightRow({ label, count, onClick }: { label: string; count: number; onClick?: () => void }) { return <PmBox component="button" onClick={onClick} sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%', px: 1, py: 1.25, border: 0, borderBottom: 1, borderColor: 'divider', bgcolor: 'transparent', color: 'text.primary', textAlign: 'left', cursor: onClick ? 'pointer' : 'default', '&:hover': { bgcolor: 'action.hover' } }}><PmText fontSize=".8rem">{label}</PmText><PmText fontSize=".8rem" fontWeight={700}>{count}</PmText></PmBox>; }
function State({ title, action }: { title: string; action?: ReactNode }) { return <PmStack sx={{ alignItems: 'center', justifyContent: 'center', minHeight: 280, gap: 1 }}><PmText color="text.secondary">{title}</PmText>{action}</PmStack>; }
