import { translateCurrentLiteral } from '../../core/i18n/I18nProvider';
export interface LowCodeExpressionHelper {
  args: Record<string, unknown>;
  name: string;
}

export interface ExpressionHelperDefinition {
  args: Array<{ key: string; label: string; placeholder?: string }>;
  group: string;
  name: string;
  title: string;
}

export const expressionHelperDefinitions: ExpressionHelperDefinition[] = [
  { args: [], group: '字符串', name: 'trim', title: '去除首尾空格' },
  { args: [], group: '字符串', name: 'ltrim', title: '去除左侧空格' },
  { args: [], group: '字符串', name: 'rtrim', title: '去除右侧空格' },
  { args: [], group: '字符串', name: 'normalizeWhitespace', title: '合并连续空白' },
  { args: [], group: '字符串', name: 'upper', title: '转大写' },
  { args: [], group: '字符串', name: 'lower', title: '转小写' },
  { args: [], group: '字符串', name: 'length', title: '文本长度' },
  { args: [{ key: 'start', label: translateCurrentLiteral("起始") }, { key: 'length', label: translateCurrentLiteral("长度") }], group: '字符串', name: 'substring', title: '截取文本' },
  { args: [{ key: 'length', label: translateCurrentLiteral("长度") }], group: '字符串', name: 'left', title: '左侧截取' },
  { args: [{ key: 'length', label: translateCurrentLiteral("长度") }], group: '字符串', name: 'right', title: '右侧截取' },
  { args: [{ key: 'oldValue', label: translateCurrentLiteral("原值") }, { key: 'newValue', label: translateCurrentLiteral("新值") }], group: '字符串', name: 'replace', title: '替换文本' },
  { args: [{ key: 'value', label: translateCurrentLiteral("移除值") }], group: '字符串', name: 'remove', title: '移除文本' },
  { args: [{ key: 'prefix', label: translateCurrentLiteral("前缀") }], group: '字符串', name: 'prefix', title: '添加前缀' },
  { args: [{ key: 'suffix', label: translateCurrentLiteral("后缀") }], group: '字符串', name: 'suffix', title: '添加后缀' },
  { args: [{ key: 'length', label: translateCurrentLiteral("总长度") }, { key: 'char', label: translateCurrentLiteral("填充符") }], group: '字符串', name: 'padLeft', title: '左侧补齐' },
  { args: [{ key: 'length', label: translateCurrentLiteral("总长度") }, { key: 'char', label: translateCurrentLiteral("填充符") }], group: '字符串', name: 'padRight', title: '右侧补齐' },
  { args: [{ key: 'separator', label: translateCurrentLiteral("分隔符") }, { key: 'index', label: translateCurrentLiteral("序号") }], group: '字符串', name: 'splitTake', title: '分割取值' },
  { args: [{ key: 'value', label: translateCurrentLiteral("默认值") }], group: '字符串', name: 'defaultIfEmpty', title: '空值默认' },
  { args: [], group: '字符串', name: 'capitalize', title: '首字母大写' },
  { args: [], group: '字符串', name: 'titleCase', title: '标题格式' },
  { args: [], group: '字符串', name: 'camelCase', title: '驼峰格式' },
  { args: [], group: '字符串', name: 'snakeCase', title: '下划线格式' },
  { args: [], group: '字符串', name: 'kebabCase', title: '短横线格式' },
  { args: [], group: '字符串', name: 'removeSpaces', title: '移除全部空格' },
  { args: [], group: '字符串', name: 'removeLineBreaks', title: '移除换行' },
  { args: [], group: '字符串', name: 'stripHtml', title: '去除 HTML' },
  { args: [], group: '字符串', name: 'onlyDigits', title: '只保留数字' },
  { args: [], group: '字符串', name: 'onlyLetters', title: '只保留字母' },
  { args: [{ key: 'length', label: translateCurrentLiteral("长度") }, { key: 'suffix', label: translateCurrentLiteral("后缀") }], group: '字符串', name: 'truncate', title: '超长截断' },
  { args: [{ key: 'separator', label: translateCurrentLiteral("分隔符") }], group: '字符串', name: 'textBefore', title: '取分隔符之前' },
  { args: [{ key: 'separator', label: translateCurrentLiteral("分隔符") }], group: '字符串', name: 'textAfter', title: '取分隔符之后' },
  { args: [{ key: 'start', label: translateCurrentLiteral("开始文本") }, { key: 'end', label: translateCurrentLiteral("结束文本") }], group: '字符串', name: 'textBetween', title: '取两段文本之间' },
  { args: [{ key: 'prefix', label: translateCurrentLiteral("前缀") }], group: '字符串', name: 'ensurePrefix', title: '确保前缀' },
  { args: [{ key: 'suffix', label: translateCurrentLiteral("后缀") }], group: '字符串', name: 'ensureSuffix', title: '确保后缀' },
  { args: [{ key: 'prefix', label: translateCurrentLiteral("前缀") }], group: '字符串', name: 'removePrefix', title: '移除指定前缀' },
  { args: [{ key: 'suffix', label: translateCurrentLiteral("后缀") }], group: '字符串', name: 'removeSuffix', title: '移除指定后缀' },
  { args: [{ key: 'count', label: translateCurrentLiteral("次数") }], group: '字符串', name: 'repeat', title: '重复文本' },
  { args: [{ key: 'count', label: translateCurrentLiteral("行数") }], group: '字符串', name: 'takeLines', title: '取前 N 行' },
  { args: [], group: '字符串', name: 'normalizeNewlines', title: '统一换行符' },
  { args: [], group: '字符串', name: 'containsChinese', title: '包含中文' },
  { args: [], group: '字符串', name: 'onlyChinese', title: '只保留中文' },
  { args: [], group: '类型转换', name: 'toString', title: '转文本' },
  { args: [], group: '类型转换', name: 'toNumber', title: '转数字' },
  { args: [], group: '类型转换', name: 'toBoolean', title: '转布尔' },
  { args: [], group: '类型转换', name: 'toInteger', title: '转整数' },
  { args: [], group: '类型转换', name: 'toArray', title: '转数组' },
  { args: [], group: '类型转换', name: 'toObject', title: '转对象' },
  { args: [], group: '类型转换', name: 'nullIfEmpty', title: '空值转 Null' },
  { args: [], group: '类型转换', name: 'emptyToNull', title: '空字符串转 Null' },
  { args: [], group: '类型转换', name: 'parseCurrency', title: '金额文本转数字' },
  { args: [], group: '编码', name: 'encodeUri', title: 'URI 编码' },
  { args: [], group: '编码', name: 'decodeUri', title: 'URI 解码' },
  { args: [], group: '编码', name: 'base64Encode', title: 'Base64 编码' },
  { args: [], group: '编码', name: 'base64Decode', title: 'Base64 解码' },
  { args: [], group: '数值', name: 'abs', title: '绝对值' },
  { args: [{ key: 'digits', label: translateCurrentLiteral("位数") }], group: '数值', name: 'round', title: '四舍五入' },
  { args: [], group: '数值', name: 'ceil', title: '向上取整' },
  { args: [], group: '数值', name: 'floor', title: '向下取整' },
  { args: [{ key: 'digits', label: translateCurrentLiteral("小数位") }], group: '数值', name: 'fixed', title: '固定小数' },
  { args: [{ key: 'symbol', label: translateCurrentLiteral("符号") }], group: '数值', name: 'currency', title: '金额格式' },
  { args: [{ key: 'digits', label: translateCurrentLiteral("小数位") }], group: '数值', name: 'percent', title: '百分比' },
  { args: [{ key: 'value', label: translateCurrentLiteral("加数") }], group: '数值', name: 'add', title: '加' },
  { args: [{ key: 'value', label: translateCurrentLiteral("减数") }], group: '数值', name: 'subtract', title: '减' },
  { args: [{ key: 'value', label: translateCurrentLiteral("乘数") }], group: '数值', name: 'multiply', title: '乘' },
  { args: [{ key: 'value', label: translateCurrentLiteral("除数") }], group: '数值', name: 'divide', title: '除' },
  { args: [{ key: 'min', label: translateCurrentLiteral("最小") }, { key: 'max', label: translateCurrentLiteral("最大") }], group: '数值', name: 'clamp', title: '限制范围' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '数值', name: 'min', title: '取较小值' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '数值', name: 'max', title: '取较大值' },
  { args: [{ key: 'value', label: translateCurrentLiteral("除数") }], group: '数值', name: 'modulo', title: '取余' },
  { args: [{ key: 'value', label: translateCurrentLiteral("指数") }], group: '数值', name: 'power', title: '幂运算' },
  { args: [], group: '数值', name: 'negate', title: '取相反数' },
  { args: [], group: '日期', name: 'parseDate', title: '转日期' },
  { args: [{ key: 'format', label: translateCurrentLiteral("格式"), placeholder: 'yyyy-MM-dd' }], group: '日期', name: 'formatDate', title: '格式化日期' },
  { args: [], group: '日期', name: 'now', title: '当前时间' },
  { args: [{ key: 'days', label: translateCurrentLiteral("天数") }], group: '日期', name: 'addDays', title: '日期加天' },
  { args: [{ key: 'hours', label: translateCurrentLiteral("小时") }], group: '日期', name: 'addHours', title: '日期加小时' },
  { args: [{ key: 'minutes', label: translateCurrentLiteral("分钟") }], group: '日期', name: 'addMinutes', title: '日期加分钟' },
  { args: [{ key: 'seconds', label: translateCurrentLiteral("秒数") }], group: '日期', name: 'addSeconds', title: '日期加秒' },
  { args: [{ key: 'months', label: translateCurrentLiteral("月数") }], group: '日期', name: 'addMonths', title: '日期加月' },
  { args: [{ key: 'years', label: translateCurrentLiteral("年数") }], group: '日期', name: 'addYears', title: '日期加年' },
  { args: [{ key: 'weeks', label: translateCurrentLiteral("周数") }], group: '日期', name: 'addWeeks', title: '日期加周' },
  { args: [], group: '日期', name: 'startOfDay', title: '当天开始' },
  { args: [], group: '日期', name: 'endOfDay', title: '当天结束' },
  { args: [], group: '日期', name: 'startOfMonth', title: '当月开始' },
  { args: [], group: '日期', name: 'endOfMonth', title: '当月结束' },
  { args: [], group: '日期', name: 'startOfYear', title: '当年开始' },
  { args: [], group: '日期', name: 'endOfYear', title: '当年结束' },
  { args: [], group: '日期', name: 'year', title: '取年份' },
  { args: [], group: '日期', name: 'month', title: '取月份' },
  { args: [], group: '日期', name: 'day', title: '取日期' },
  { args: [], group: '日期', name: 'today', title: '今天' },
  { args: [], group: '日期', name: 'yesterday', title: '昨天' },
  { args: [], group: '日期', name: 'tomorrow', title: '明天' },
  { args: [], group: '日期', name: 'weekOfYear', title: '取周序号' },
  { args: [], group: '日期', name: 'weekday', title: '取星期' },
  { args: [], group: '日期', name: 'quarter', title: '取季度' },
  { args: [], group: '日期', name: 'formatQuarter', title: '格式化季度' },
  { args: [], group: '日期', name: 'ageYears', title: '按生日算年龄' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较日期") }], group: '日期', name: 'diffDays', title: '相差天数' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较日期") }], group: '日期', name: 'diffHours', title: '相差小时' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较日期") }], group: '日期', name: 'diffMinutes', title: '相差分钟' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较日期") }], group: '日期', name: 'diffSeconds', title: '相差秒数' },
  { args: [], group: '日期', name: 'timestamp', title: '转时间戳' },
  { args: [], group: '日期', name: 'fromTimestamp', title: '时间戳转日期' },
  { args: [{ key: 'path', label: translateCurrentLiteral("路径"), placeholder: '$.data.items' }], group: 'JSON/集合', name: 'jsonPath', title: '读取 JSON 路径' },
  { args: [], group: 'JSON/集合', name: 'parseJson', title: '解析 JSON' },
  { args: [], group: 'JSON/集合', name: 'stringifyJson', title: '转 JSON 文本' },
  { args: [], group: 'JSON/集合', name: 'objectKeys', title: '对象键集合' },
  { args: [], group: 'JSON/集合', name: 'objectValues', title: '对象值集合' },
  { args: [], group: 'JSON/集合', name: 'first', title: '取第一项' },
  { args: [], group: 'JSON/集合', name: 'last', title: '取最后一项' },
  { args: [{ key: 'index', label: translateCurrentLiteral("序号") }], group: 'JSON/集合', name: 'nth', title: '取第 N 项' },
  { args: [], group: 'JSON/集合', name: 'count', title: '计数' },
  { args: [{ key: 'count', label: translateCurrentLiteral("数量") }], group: 'JSON/集合', name: 'take', title: '取前 N 项' },
  { args: [{ key: 'count', label: translateCurrentLiteral("数量") }], group: 'JSON/集合', name: 'skip', title: '跳过 N 项' },
  { args: [{ key: 'start', label: translateCurrentLiteral("起始") }, { key: 'count', label: translateCurrentLiteral("数量") }], group: 'JSON/集合', name: 'slice', title: '集合截取' },
  { args: [{ key: 'pageIndex', label: translateCurrentLiteral("页码") }, { key: 'pageSize', label: translateCurrentLiteral("每页数量") }], group: 'JSON/集合', name: 'page', title: '集合分页' },
  { args: [], group: 'JSON/集合', name: 'reverse', title: '反转集合' },
  { args: [], group: 'JSON/集合', name: 'distinct', title: '去重' },
  { args: [], group: 'JSON/集合', name: 'compact', title: '去除空项' },
  { args: [], group: 'JSON/集合', name: 'filterNotEmpty', title: '过滤非空项' },
  { args: [], group: 'JSON/集合', name: 'emptyArrayIfNull', title: '空值转空数组' },
  { args: [{ key: 'separator', label: translateCurrentLiteral("分隔符") }], group: 'JSON/集合', name: 'join', title: '拼接集合' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }], group: 'JSON/集合', name: 'mapField', title: '提取字段集合' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }, { key: 'value', label: translateCurrentLiteral("匹配值") }], group: 'JSON/集合', name: 'filterEquals', title: '按字段等值过滤' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }, { key: 'value', label: translateCurrentLiteral("包含值") }], group: 'JSON/集合', name: 'filterContains', title: '按字段包含过滤' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }, { key: 'value', label: translateCurrentLiteral("排除值") }], group: 'JSON/集合', name: 'rejectEquals', title: '按字段排除' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }, { key: 'value', label: translateCurrentLiteral("匹配值") }], group: 'JSON/集合', name: 'findByField', title: '查找单条记录' },
  { args: [{ key: 'value', label: translateCurrentLiteral("匹配值") }], group: 'JSON/集合', name: 'containsItem', title: '集合包含值' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }, { key: 'direction', label: translateCurrentLiteral("方向"), placeholder: 'asc/desc' }], group: 'JSON/集合', name: 'sortBy', title: '按字段排序' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }], group: 'JSON/集合', name: 'uniqueBy', title: '按字段去重' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }], group: 'JSON/集合', name: 'groupBy', title: '按字段分组' },
  { args: [], group: 'JSON/集合', name: 'flatten', title: '拉平集合' },
  { args: [{ key: 'path', label: translateCurrentLiteral("路径") }], group: '对象', name: 'objectPath', title: '读取对象路径' },
  { args: [{ key: 'path', label: translateCurrentLiteral("路径") }], group: '对象', name: 'hasPath', title: '是否存在路径' },
  { args: [{ key: 'fields', label: translateCurrentLiteral("字段列表"), placeholder: 'id,name,status' }], group: '对象', name: 'pickFields', title: '保留字段' },
  { args: [{ key: 'fields', label: translateCurrentLiteral("字段列表"), placeholder: 'password,token' }], group: '对象', name: 'omitFields', title: '排除字段' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }], group: 'JSON/集合', name: 'sum', title: '求和' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }], group: 'JSON/集合', name: 'average', title: '平均值' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }], group: 'JSON/集合', name: 'minBy', title: '字段最小值' },
  { args: [{ key: 'field', label: translateCurrentLiteral("字段") }], group: 'JSON/集合', name: 'maxBy', title: '字段最大值' },
  { args: [{ key: 'value', label: translateCurrentLiteral("候选值") }], group: '通用', name: 'coalesce', title: '空值合并' },
  { args: [], group: '通用', name: 'isEmpty', title: '是否为空' },
  { args: [], group: '通用', name: 'isNotEmpty', title: '是否非空' },
  { args: [], group: '通用', name: 'isNull', title: '是否 Null' },
  { args: [], group: '通用', name: 'isNotNull', title: '是否非 Null' },
  { args: [], group: '通用', name: 'isTrue', title: '是否为真' },
  { args: [], group: '通用', name: 'isFalse', title: '是否为假' },
  { args: [], group: '通用', name: 'isString', title: '是否文本' },
  { args: [], group: '通用', name: 'isBoolean', title: '是否布尔' },
  { args: [], group: '通用', name: 'isArray', title: '是否数组' },
  { args: [], group: '通用', name: 'isObject', title: '是否对象' },
  { args: [], group: '通用', name: 'not', title: '逻辑取反' },
  { args: [{ key: 'value', label: translateCurrentLiteral("布尔值") }], group: '通用', name: 'and', title: '并且' },
  { args: [{ key: 'value', label: translateCurrentLiteral("布尔值") }], group: '通用', name: 'or', title: '或者' },
  { args: [{ key: 'whenTrue', label: translateCurrentLiteral("为真返回") }, { key: 'whenFalse', label: translateCurrentLiteral("为假返回") }], group: '通用', name: 'ifElse', title: '条件返回' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '通用', name: 'equals', title: '等于' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '通用', name: 'notEquals', title: '不等于' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '通用', name: 'greaterThan', title: '大于' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '通用', name: 'greaterOrEquals', title: '大于等于' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '通用', name: 'lessThan', title: '小于' },
  { args: [{ key: 'value', label: translateCurrentLiteral("比较值") }], group: '通用', name: 'lessOrEquals', title: '小于等于' },
  { args: [{ key: 'value', label: translateCurrentLiteral("包含值") }], group: '通用', name: 'contains', title: '包含' },
  { args: [{ key: 'value', label: translateCurrentLiteral("前缀") }], group: '通用', name: 'startsWith', title: '以...开头' },
  { args: [{ key: 'value', label: translateCurrentLiteral("后缀") }], group: '通用', name: 'endsWith', title: '以...结尾' },
  { args: [{ key: 'values', label: translateCurrentLiteral("候选值"), placeholder: 'A,B,C' }], group: '通用', name: 'inList', title: '在列表中' },
  { args: [], group: '校验', name: 'isNumber', title: '是否数字' },
  { args: [], group: '校验', name: 'isInteger', title: '是否整数' },
  { args: [], group: '校验', name: 'isPositive', title: '是否正数' },
  { args: [], group: '校验', name: 'isNegative', title: '是否负数' },
  { args: [], group: '校验', name: 'isZero', title: '是否为零' },
  { args: [], group: '校验', name: 'isDate', title: '是否日期' },
  { args: [], group: '校验', name: 'isEmail', title: '是否邮箱' },
  { args: [], group: '校验', name: 'isPhone', title: '是否手机号' },
  { args: [], group: '校验', name: 'isUrl', title: '是否 URL' },
  { args: [], group: '校验', name: 'isGuid', title: '是否 GUID' },
  { args: [], group: '校验', name: 'isJson', title: '是否 JSON' },
  { args: [], group: '校验', name: 'isPostalCode', title: '是否邮编' },
  { args: [{ key: 'length', label: translateCurrentLiteral("长度") }], group: '校验', name: 'minLength', title: '最小长度通过' },
  { args: [{ key: 'length', label: translateCurrentLiteral("长度") }], group: '校验', name: 'maxLength', title: '最大长度通过' },
  { args: [{ key: 'min', label: translateCurrentLiteral("最小") }, { key: 'max', label: translateCurrentLiteral("最大") }], group: '校验', name: 'between', title: '数值区间通过' },
  { args: [], group: '脱敏/展示', name: 'maskPhone', title: '手机号脱敏' },
  { args: [], group: '脱敏/展示', name: 'maskEmail', title: '邮箱脱敏' },
  { args: [], group: '脱敏/展示', name: 'maskIdCard', title: '身份证脱敏' },
  { args: [], group: '脱敏/展示', name: 'maskBankCard', title: '银行卡脱敏' },
  { args: [], group: '脱敏/展示', name: 'maskName', title: '姓名脱敏' },
  { args: [{ key: 'start', label: translateCurrentLiteral("保留前") }, { key: 'end', label: translateCurrentLiteral("保留后") }, { key: 'mask', label: translateCurrentLiteral("掩码") }], group: '脱敏/展示', name: 'maskText', title: '文本脱敏' },
  { args: [{ key: 'trueText', label: translateCurrentLiteral("真值文本") }, { key: 'falseText', label: translateCurrentLiteral("假值文本") }], group: '脱敏/展示', name: 'booleanText', title: '布尔文本' },
  { args: [], group: '脱敏/展示', name: 'yesNo', title: '是/否文本' },
  { args: [], group: '脱敏/展示', name: 'enabledDisabled', title: '启用/禁用文本' },
  { args: [], group: '脱敏/展示', name: 'successFail', title: '成功/失败文本' },
  { args: [{ key: 'mapping', label: translateCurrentLiteral("映射表"), placeholder: '0=禁用;1=启用' }, { key: 'defaultValue', label: translateCurrentLiteral("默认值") }], group: '脱敏/展示', name: 'mapValue', title: '值映射文本' }
];

export function createExpressionHelper<T extends LowCodeExpressionHelper = LowCodeExpressionHelper>(name: string): T {
  const definition = expressionHelperDefinitions.find((item) => item.name === name);
  return {
    args: Object.fromEntries((definition?.args ?? []).map((arg) => [arg.key, ''])),
    name
  } as T;
}
