export const projectManagementCollaborationMessagesZhCN = {
  'projectManagement.editor.create': '新建任务', 'projectManagement.editor.edit': '编辑任务', 'projectManagement.editor.titleAria': '任务标题', 'projectManagement.editor.titlePlaceholder': '输入任务标题', 'projectManagement.editor.descriptionAria': '任务描述', 'projectManagement.editor.descriptionPlaceholder': '描述任务背景、目标和验收标准；输入 @ 可提及项目成员',
  'projectManagement.editor.continueCreating': '保存后继续创建', 'projectManagement.editor.cancel': '取消', 'projectManagement.editor.save': '保存', 'projectManagement.editor.savedCreate': '任务已创建', 'projectManagement.editor.savedUpdate': '任务已更新', 'projectManagement.editor.saveFailed': '保存失败', 'projectManagement.editor.conflict': '保存发生并发冲突，本地草稿已保留',
  'projectManagement.editor.closeTitle': '关闭任务编辑', 'projectManagement.editor.closeDescription': '存在未保存修改或草稿附件，是否放弃当前编辑？', 'projectManagement.editor.discard': '放弃修改',
  'projectManagement.editor.attachment': '附件', 'projectManagement.editor.upload': '上传附件', 'projectManagement.editor.uploaded': '附件已上传', 'projectManagement.editor.uploadFailed': '附件上传失败，草稿仍保留',
  'projectManagement.editor.comment': '评论', 'projectManagement.editor.commentAria': '新增评论', 'projectManagement.editor.commentPlaceholder': '添加评论，输入 @ 提及成员', 'projectManagement.editor.publishComment': '发表评论', 'projectManagement.editor.commentPublished': '评论已发布', 'projectManagement.editor.afterSaveHint': '保存后可发表评论与管理关注人。',
  'projectManagement.editor.field.project': '项目', 'projectManagement.editor.field.workItemType': '工作项类型', 'projectManagement.editor.field.status': '状态', 'projectManagement.editor.field.assignee': '负责人', 'projectManagement.editor.field.parent': '父工作项', 'projectManagement.editor.field.milestone': '里程碑', 'projectManagement.editor.field.startDate': '开始时间', 'projectManagement.editor.field.dueDate': '结束时间', 'projectManagement.editor.field.priority': '优先级', 'projectManagement.editor.field.risk': '风险', 'projectManagement.editor.field.requirementType': '任务类型', 'projectManagement.editor.field.requirementSource': '任务来源', 'projectManagement.editor.field.followers': '关注人',
  'projectManagement.editor.currentProject': '当前项目', 'projectManagement.editor.conflictDetected': '检测到并发修改，本地草稿已保留', 'projectManagement.editor.server': '服务器', 'projectManagement.editor.local': '本地', 'projectManagement.editor.reload': '加载服务器值', 'projectManagement.editor.keepLocal': '保留本地草稿', 'projectManagement.editor.overwrite': '覆盖保存'
  ,'projectManagement.richEditor.loading': '正在加载编辑器…', 'projectManagement.richEditor.toolbar': '富文本工具栏', 'projectManagement.richEditor.paragraph': '段落', 'projectManagement.richEditor.heading': '标题', 'projectManagement.richEditor.bold': '粗体', 'projectManagement.richEditor.italic': '斜体', 'projectManagement.richEditor.strike': '删除线', 'projectManagement.richEditor.bulletList': '无序列表', 'projectManagement.richEditor.orderedList': '有序列表', 'projectManagement.richEditor.quote': '引用', 'projectManagement.richEditor.link': '链接', 'projectManagement.richEditor.linkPrompt': '链接地址', 'projectManagement.richEditor.mention': '@成员', 'projectManagement.richEditor.undo': '撤销', 'projectManagement.richEditor.redo': '重做', 'projectManagement.richEditor.placeholder': '请输入内容', 'projectManagement.richEditor.searchMembers': '搜索成员…', 'projectManagement.richEditor.noMembers': '没有匹配的项目成员'
} as const;
