export const projectManagementOperationsMessagesZhCN = {
  'projectManagement.operation.retry': '重试',
  'projectManagement.operation.loading': '正在加载…',
  'projectManagement.operation.loadFailed': '加载失败',
  'projectManagement.operation.unknownError': '操作失败，请稍后重试。'
  ,'projectManagement.notification.title': '项目通知', 'projectManagement.notification.all': '全部', 'projectManagement.notification.unread': '未读', 'projectManagement.notification.markAllRead': '全部已读', 'projectManagement.notification.markRead': '标记已读', 'projectManagement.notification.typeAria': '通知类型', 'projectManagement.notification.unavailable': '关联对象不可访问', 'projectManagement.notification.markAllFailed': '全部标记已读失败', 'projectManagement.notification.markReadFailed': '标记已读失败', 'projectManagement.notification.openFailed': '通知打开失败', 'projectManagement.notification.realtimeUnavailable': '实时连接暂不可用，通知仍会保存在站内；连接恢复后自动刷新。', 'projectManagement.notification.enableBrowser': '启用任务提醒和高价值通知', 'projectManagement.notification.browserDenied': '浏览器通知已被拒绝，将仅显示站内通知。', 'projectManagement.notification.loading': '正在加载通知…', 'projectManagement.notification.loadFailed': '通知加载失败。', 'projectManagement.notification.empty': '暂无项目通知', 'projectManagement.notification.countOverflow': '99+',
  'projectManagement.notification.type.all': '全部类型', 'projectManagement.notification.type.taskReminder': '任务提醒', 'projectManagement.notification.type.mentioned': '@ 提及', 'projectManagement.notification.type.assigned': '任务分配', 'projectManagement.notification.type.participantAdded': '加入参与人', 'projectManagement.notification.type.participantRemoved': '移出参与人', 'projectManagement.notification.type.statusChanged': '任务状态', 'projectManagement.notification.type.dueDateChanged': '截止日期', 'projectManagement.notification.type.milestoneRisk': '里程碑风险', 'projectManagement.notification.type.excelImport': 'Excel 导入', 'projectManagement.notification.type.syncExport': '同步导出', 'projectManagement.notification.type.syncImport': '同步导入', 'projectManagement.notification.type.succeeded': '操作完成', 'projectManagement.notification.type.failed': '操作失败'
  ,'projectManagement.api.notification.open.auditDenied': '无权访问关联操作记录', 'projectManagement.api.notification.open.syncDenied': '无权访问项目同步', 'projectManagement.api.notification.open.unavailable': '通知未关联可打开的项目对象', 'projectManagement.api.notification.open.targetUnavailable': '关联项目或任务已删除，或你已无权访问'
} as const;
