export const projectManagementCollaborationMessagesZhCN = {
  'projectManagement.editor.create': '新建任务', 'projectManagement.editor.edit': '编辑任务', 'projectManagement.editor.titleAria': '任务标题', 'projectManagement.editor.titlePlaceholder': '输入任务标题', 'projectManagement.editor.descriptionAria': '任务描述', 'projectManagement.editor.descriptionPlaceholder': '描述任务背景、目标和验收标准；输入 @ 可提及项目成员',
  'projectManagement.editor.continueCreating': '保存后继续创建', 'projectManagement.editor.cancel': '取消', 'projectManagement.editor.save': '保存', 'projectManagement.editor.savedCreate': '任务已创建', 'projectManagement.editor.savedUpdate': '任务已更新', 'projectManagement.editor.saveFailed': '保存失败', 'projectManagement.editor.conflict': '保存发生并发冲突，本地草稿已保留',
  'projectManagement.editor.closeTitle': '关闭任务编辑', 'projectManagement.editor.closeDescription': '存在未保存修改或草稿附件，是否放弃当前编辑？', 'projectManagement.editor.discard': '放弃修改',
  'projectManagement.editor.attachment': '附件',
  'projectManagement.editor.comment': '评论', 'projectManagement.editor.comment.empty': '暂无评论，来发表第一条评论吧。', 'projectManagement.editor.comment.editedAt': '编辑于 {time}', 'projectManagement.editor.commentAria': '新增评论', 'projectManagement.editor.commentPlaceholder': '添加评论，输入 @ 提及任意部门人员', 'projectManagement.editor.publishComment': '发表评论', 'projectManagement.editor.commentPublished': '评论已发布', 'projectManagement.editor.commentPublishFailed': '评论发布失败', 'projectManagement.editor.commentReadOnly': '你可查看评论，但没有发表评论权限。', 'projectManagement.editor.allowMentionedComment': '允许被 @ 的项目外人员在此任务发表评论', 'projectManagement.editor.sharedReadOnly': '此任务通过 @ 提及共享给你；除评论外仅可查看。', 'projectManagement.editor.afterSaveHint': '保存后可发表评论与管理参与人。', 'projectManagement.editor.addParticipant': '添加参与人', 'projectManagement.editor.participantAdded': '参与人已添加', 'projectManagement.editor.participantRemoved': '参与人已移除', 'projectManagement.editor.participantFailed': '参与人操作失败',
  'projectManagement.editor.field.project': '项目', 'projectManagement.editor.field.workItemType': '工作项类型', 'projectManagement.editor.field.status': '状态', 'projectManagement.editor.field.assignee': '负责人', 'projectManagement.editor.field.parent': '父工作项', 'projectManagement.editor.field.milestone': '里程碑', 'projectManagement.editor.field.startDate': '开始时间', 'projectManagement.editor.field.dueDate': '结束时间', 'projectManagement.editor.field.priority': '优先级', 'projectManagement.editor.field.risk': '风险', 'projectManagement.editor.field.requirementType': '任务类型', 'projectManagement.editor.field.requirementSource': '任务来源', 'projectManagement.editor.field.followers': '参与人', 'projectManagement.editor.field.progress': '进度', 'projectManagement.editor.field.estimateMinutes': '预计工时（分钟）', 'projectManagement.editor.field.actualMinutes': '已登记工时（分钟）',
  'projectManagement.editor.group.basic': '基本信息', 'projectManagement.editor.group.schedule': '计划安排', 'projectManagement.editor.group.classification': '分类属性',
  'projectManagement.editor.currentProject': '当前项目', 'projectManagement.editor.conflictDetected': '检测到并发修改，本地草稿已保留', 'projectManagement.editor.server': '服务器', 'projectManagement.editor.local': '本地', 'projectManagement.editor.reload': '加载服务器值', 'projectManagement.editor.keepLocal': '保留本地草稿', 'projectManagement.editor.overwrite': '覆盖保存',
  'projectManagement.editor.tab.details': '详情', 'projectManagement.editor.tab.comments': '评论', 'projectManagement.editor.tab.attachments': '附件', 'projectManagement.editor.tab.reminders': '提醒', 'projectManagement.editor.tab.timeLogs': '工时', 'projectManagement.editor.tab.activity': '进度&活动',
  'projectManagement.editor.download': '下载', 'projectManagement.editor.preview': '预览', 'projectManagement.editor.previewUnsupported': '此文件不支持在线预览，可下载后查看', 'projectManagement.editor.previewFailed': '预览加载失败', 'projectManagement.editor.attachFile': '附加文件', 'projectManagement.editor.removeFile': '移除',
  'projectManagement.editor.reminder.title': '提醒', 'projectManagement.editor.reminder.add': '添加提醒', 'projectManagement.editor.reminder.at': '提醒时间', 'projectManagement.editor.reminder.scope': '接收范围', 'projectManagement.editor.reminder.note': '备注', 'projectManagement.editor.reminder.created': '提醒已创建', 'projectManagement.editor.reminder.canceled': '提醒已取消', 'projectManagement.editor.reminder.deleted': '提醒已删除', 'projectManagement.editor.reminder.failed': '提醒操作失败', 'projectManagement.editor.reminder.empty': '暂无提醒', 'projectManagement.editor.reminder.cancel': '取消提醒', 'projectManagement.editor.reminder.delete': '删除', 'projectManagement.editor.reminder.scope.Self': '自己', 'projectManagement.editor.reminder.scope.Assignee': '负责人', 'projectManagement.editor.reminder.scope.Participants': '参与人', 'projectManagement.editor.reminder.scope.Members': '项目成员',
  'projectManagement.editor.timeLog.title': '工时', 'projectManagement.editor.timeLog.add': '登记工时', 'projectManagement.editor.timeLog.startedAt': '开始', 'projectManagement.editor.timeLog.endedAt': '结束', 'projectManagement.editor.timeLog.minutes': '分钟', 'projectManagement.editor.timeLog.note': '备注', 'projectManagement.editor.timeLog.empty': '暂无工时记录', 'projectManagement.editor.timeLog.created': '工时已登记', 'projectManagement.editor.timeLog.deleted': '工时已删除', 'projectManagement.editor.timeLog.failed': '工时操作失败', 'projectManagement.editor.timeLog.summary': '预计 {estimate} 分钟 · 已登记 {actual} 分钟', 'projectManagement.editor.timeLog.delete': '删除',
  'projectManagement.editor.saveFirst': '请先保存任务后再使用此功能。'
  ,'projectManagement.richEditor.loading': '正在加载编辑器…', 'projectManagement.richEditor.toolbar': '富文本工具栏', 'projectManagement.richEditor.paragraph': '段落', 'projectManagement.richEditor.heading': '标题', 'projectManagement.richEditor.bold': '粗体', 'projectManagement.richEditor.italic': '斜体', 'projectManagement.richEditor.strike': '删除线', 'projectManagement.richEditor.bulletList': '无序列表', 'projectManagement.richEditor.orderedList': '有序列表', 'projectManagement.richEditor.quote': '引用', 'projectManagement.richEditor.link': '链接地址', 'projectManagement.richEditor.mention': '@成员', 'projectManagement.richEditor.undo': '撤销', 'projectManagement.richEditor.redo': '重做', 'projectManagement.richEditor.placeholder': '请输入内容', 'projectManagement.richEditor.searchMembers': '正在搜索人员…', 'projectManagement.richEditor.noMembers': '没有匹配的人员'
} as const;
