import { ContainerInspectorDefinitionBase } from './ContainerInspectorDefinitionBase';

export abstract class LayoutDocumentInspectorDefinitionBase extends ContainerInspectorDefinitionBase {
  protected constructor(componentType: string) {
    super(componentType);
    this.property({ path: 'layout.layoutMode', section: 'layout', order: 40, editor: 'select', valueType: 'string', defaultValue: 'free', labelKey: 'lowCode.inspector.layout.mode.label', helpKey: 'lowCode.inspector.layout.mode.help', fallbackLabel: 'Layout mode', runtimeConsumer: 'runtime.component.layout', options: [{ label: 'Free', value: 'free' }, { label: 'Flex', value: 'flex' }, { label: 'Grid', value: 'grid' }, { label: 'Constraints', value: 'constraints' }] });
    this.property({ path: 'layout.flexDirection', section: 'layout', order: 50, editor: 'select', valueType: 'string', defaultValue: 'row', labelKey: 'lowCode.inspector.layout.flexDirection.label', helpKey: 'lowCode.inspector.layout.flexDirection.help', fallbackLabel: 'Flex direction', runtimeConsumer: 'runtime.component.layout', options: [{ label: 'Row', value: 'row' }, { label: 'Column', value: 'column' }], visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'flex' } });
    this.property({ path: 'layout.gap', section: 'layout', order: 60, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.layout.gap.label', helpKey: 'lowCode.inspector.layout.gap.help', fallbackLabel: 'Gap', runtimeConsumer: 'runtime.component.layout', unit: 'px', validation: { valueType: 'number', min: 0 }, visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'flex' } });
    this.property({ path: 'layout.alignItems', section: 'layout', order: 70, editor: 'select', valueType: 'string', defaultValue: 'flex-start', labelKey: 'lowCode.inspector.layout.alignItems.label', helpKey: 'lowCode.inspector.layout.alignItems.help', fallbackLabel: 'Align items', runtimeConsumer: 'runtime.component.layout', options: [{ label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }, { label: 'Stretch', value: 'stretch' }] });
    this.property({ path: 'layout.justifyContent', section: 'layout', order: 80, editor: 'select', valueType: 'string', defaultValue: 'flex-start', labelKey: 'lowCode.inspector.layout.justifyContent.label', helpKey: 'lowCode.inspector.layout.justifyContent.help', fallbackLabel: 'Justify content', runtimeConsumer: 'runtime.component.layout', options: [{ label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }, { label: 'Space between', value: 'space-between' }], visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'flex' } });
    this.property({ path: 'layout.flex', section: 'layout', order: 90, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.layout.flex.label', helpKey: 'lowCode.inspector.layout.flex.help', fallbackLabel: 'Flex', runtimeConsumer: 'runtime.component.layout', visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'flex' } });
    this.property({ path: 'layout.flexGrow', section: 'layout', order: 100, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.layout.flexGrow.label', helpKey: 'lowCode.inspector.layout.flexGrow.help', fallbackLabel: 'Flex grow', runtimeConsumer: 'runtime.component.layout', validation: { valueType: 'number', min: 0 }, visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'flex' } });
    this.property({ path: 'layout.flexShrink', section: 'layout', order: 110, editor: 'number', valueType: 'number', defaultValue: 1, labelKey: 'lowCode.inspector.layout.flexShrink.label', helpKey: 'lowCode.inspector.layout.flexShrink.help', fallbackLabel: 'Flex shrink', runtimeConsumer: 'runtime.component.layout', validation: { valueType: 'number', min: 0 }, visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'flex' } });
    this.property({ path: 'layout.flexBasis', section: 'layout', order: 120, editor: 'text', valueType: 'string', defaultValue: 'auto', labelKey: 'lowCode.inspector.layout.flexBasis.label', helpKey: 'lowCode.inspector.layout.flexBasis.help', fallbackLabel: 'Flex basis', runtimeConsumer: 'runtime.component.layout', visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'flex' } });
    this.property({ path: 'layout.columns', section: 'layout', order: 130, editor: 'number', valueType: 'number', defaultValue: 1, labelKey: 'lowCode.inspector.layout.columns.label', helpKey: 'lowCode.inspector.layout.columns.help', fallbackLabel: 'Columns', runtimeConsumer: 'runtime.component.layout', validation: { valueType: 'number', integer: true, min: 1 }, visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'grid' } });
    this.property({ path: 'layout.rows', section: 'layout', order: 140, editor: 'number', valueType: 'number', defaultValue: 1, labelKey: 'lowCode.inspector.layout.rows.label', helpKey: 'lowCode.inspector.layout.rows.help', fallbackLabel: 'Rows', runtimeConsumer: 'runtime.component.layout', validation: { valueType: 'number', integer: true, min: 1 }, visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'grid' } });
    this.property({ path: 'layout.gridTemplateColumns', section: 'layout', order: 150, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.layout.gridTemplateColumns.label', helpKey: 'lowCode.inspector.layout.gridTemplateColumns.help', fallbackLabel: 'Grid columns', runtimeConsumer: 'runtime.component.layout', visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'grid' } });
    this.property({ path: 'layout.gridTemplateRows', section: 'layout', order: 160, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.layout.gridTemplateRows.label', helpKey: 'lowCode.inspector.layout.gridTemplateRows.help', fallbackLabel: 'Grid rows', runtimeConsumer: 'runtime.component.layout', visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'grid' } });
    this.property({ path: 'layout.gridColumn', section: 'layout', order: 170, editor: 'number', valueType: 'number', defaultValue: 1, labelKey: 'lowCode.inspector.layout.gridColumn.label', helpKey: 'lowCode.inspector.layout.gridColumn.help', fallbackLabel: 'Grid column', runtimeConsumer: 'runtime.component.layout', validation: { valueType: 'number', integer: true, min: 1 }, visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'grid' } });
    this.property({ path: 'layout.gridRow', section: 'layout', order: 180, editor: 'number', valueType: 'number', defaultValue: 1, labelKey: 'lowCode.inspector.layout.gridRow.label', helpKey: 'lowCode.inspector.layout.gridRow.help', fallbackLabel: 'Grid row', runtimeConsumer: 'runtime.component.layout', validation: { valueType: 'number', integer: true, min: 1 }, visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'grid' } });
    this.property({ path: 'layout.x', section: 'layout', order: 190, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.layout.x.label', helpKey: 'lowCode.inspector.layout.x.help', fallbackLabel: 'Horizontal position', runtimeConsumer: 'runtime.component.layout', unit: 'px' });
    this.property({ path: 'layout.y', section: 'layout', order: 200, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.layout.y.label', helpKey: 'lowCode.inspector.layout.y.help', fallbackLabel: 'Vertical position', runtimeConsumer: 'runtime.component.layout', unit: 'px' });
    this.property({ path: 'layout.constraints', section: 'layout', order: 210, editor: 'json', valueType: 'object', defaultValue: {}, labelKey: 'lowCode.inspector.layout.constraints.label', helpKey: 'lowCode.inspector.layout.constraints.help', fallbackLabel: 'Constraints', runtimeConsumer: 'runtime.component.layout', visibleWhen: { path: 'layout.layoutMode', operator: 'equals', value: 'constraints' } });
    this.property({ path: 'layout.zIndex', section: 'layout', order: 220, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.layout.zIndex.label', helpKey: 'lowCode.inspector.layout.zIndex.help', fallbackLabel: 'Layer order', runtimeConsumer: 'runtime.component.layout', validation: { valueType: 'number', integer: true } });
    this.property({ path: 'layout.transform', section: 'layout', order: 230, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.layout.transform.label', helpKey: 'lowCode.inspector.layout.transform.help', fallbackLabel: 'Transform', runtimeConsumer: 'runtime.component.layout' });
  }
}
