import { ComponentInspectorDefinitionBase } from './ComponentInspectorDefinitionBase';

export abstract class VisualComponentInspectorDefinitionBase extends ComponentInspectorDefinitionBase {
  protected constructor(componentType: string) {
    super(componentType);
    this.property({ path: 'layout.width', section: 'layout', order: 10, editor: 'text', valueType: 'string', defaultValue: '100%', labelKey: 'lowCode.inspector.layout.width.label', helpKey: 'lowCode.inspector.layout.width.help', fallbackLabel: 'Width', runtimeConsumer: 'runtime.component.layout' });
    this.property({ path: 'layout.height', section: 'layout', order: 20, editor: 'text', valueType: 'string', defaultValue: 'auto', labelKey: 'lowCode.inspector.layout.height.label', helpKey: 'lowCode.inspector.layout.height.help', fallbackLabel: 'Height', runtimeConsumer: 'runtime.component.layout' });
    this.property({ path: 'layout.minHeight', section: 'layout', order: 30, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.layout.minHeight.label', helpKey: 'lowCode.inspector.layout.minHeight.help', fallbackLabel: 'Minimum height', runtimeConsumer: 'runtime.component.layout', unit: 'px', validation: { valueType: 'number', min: 0 } });
    this.property({ path: 'style.backgroundColor', section: 'appearance', order: 10, editor: 'color', valueType: 'string', defaultValue: '#ffffff', labelKey: 'lowCode.inspector.style.backgroundColor.label', helpKey: 'lowCode.inspector.style.backgroundColor.help', fallbackLabel: 'Background color', runtimeConsumer: 'runtime.component.style' });
    this.property({ path: 'style.color', section: 'appearance', order: 20, editor: 'color', valueType: 'string', defaultValue: '#111827', labelKey: 'lowCode.inspector.style.color.label', helpKey: 'lowCode.inspector.style.color.help', fallbackLabel: 'Text color', runtimeConsumer: 'runtime.component.style' });
    this.property({ path: 'style.fontFamily', section: 'appearance', order: 30, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.style.fontFamily.label', helpKey: 'lowCode.inspector.style.fontFamily.help', fallbackLabel: 'Font family', runtimeConsumer: 'runtime.component.style' });
    this.property({ path: 'style.fontSize', section: 'appearance', order: 40, editor: 'number', valueType: 'number', defaultValue: 14, labelKey: 'lowCode.inspector.style.fontSize.label', helpKey: 'lowCode.inspector.style.fontSize.help', fallbackLabel: 'Font size', runtimeConsumer: 'runtime.component.style', unit: 'px', validation: { valueType: 'number', min: 1 } });
    this.property({ path: 'style.fontWeight', section: 'appearance', order: 50, editor: 'select', valueType: 'string', defaultValue: '400', labelKey: 'lowCode.inspector.style.fontWeight.label', helpKey: 'lowCode.inspector.style.fontWeight.help', fallbackLabel: 'Font weight', runtimeConsumer: 'runtime.component.style', options: [{ label: 'Regular', value: '400' }, { label: 'Medium', value: '500' }, { label: 'Bold', value: '600' }] });
    this.property({ path: 'style.lineHeight', section: 'appearance', order: 60, editor: 'number', valueType: 'number', defaultValue: 1.4, labelKey: 'lowCode.inspector.style.lineHeight.label', helpKey: 'lowCode.inspector.style.lineHeight.help', fallbackLabel: 'Line height', runtimeConsumer: 'runtime.component.style', validation: { valueType: 'number', min: 0 } });
    this.property({ path: 'style.textAlign', section: 'appearance', order: 70, editor: 'select', valueType: 'string', defaultValue: 'left', labelKey: 'lowCode.inspector.style.textAlign.label', helpKey: 'lowCode.inspector.style.textAlign.help', fallbackLabel: 'Text align', runtimeConsumer: 'runtime.component.style', options: [{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }, { label: 'Justify', value: 'justify' }] });
    this.property({ path: 'style.textDecoration', section: 'appearance', order: 80, editor: 'select', valueType: 'string', defaultValue: 'none', labelKey: 'lowCode.inspector.style.textDecoration.label', helpKey: 'lowCode.inspector.style.textDecoration.help', fallbackLabel: 'Text decoration', runtimeConsumer: 'runtime.component.style', options: [{ label: 'None', value: 'none' }, { label: 'Underline', value: 'underline' }, { label: 'Line through', value: 'line-through' }] });
    this.property({ path: 'style.letterSpacing', section: 'appearance', order: 90, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.style.letterSpacing.label', helpKey: 'lowCode.inspector.style.letterSpacing.help', fallbackLabel: 'Letter spacing', runtimeConsumer: 'runtime.component.style', unit: 'px', validation: { valueType: 'number' } });
    this.property({ path: 'style.padding', section: 'appearance', order: 100, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.style.padding.label', helpKey: 'lowCode.inspector.style.padding.help', fallbackLabel: 'Padding', runtimeConsumer: 'runtime.component.style', unit: 'px', validation: { valueType: 'number', min: 0 } });
    this.property({ path: 'style.borderRadius', section: 'appearance', order: 110, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.style.borderRadius.label', helpKey: 'lowCode.inspector.style.borderRadius.help', fallbackLabel: 'Border radius', runtimeConsumer: 'runtime.component.style', unit: 'px', validation: { valueType: 'number', min: 0 } });
    this.property({ path: 'props.ariaLabel', section: 'advanced', order: 20, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.accessibility.ariaLabel.label', helpKey: 'lowCode.inspector.accessibility.ariaLabel.help', fallbackLabel: 'Accessible label', bindable: true, acceptedSources: ['page', 'component', 'variable'], runtimeConsumer: 'runtime.component.accessibility', accessibility: { role: 'label', labelPath: 'props.ariaLabel' } });
    this.property({ path: 'props.ariaDescription', section: 'advanced', order: 30, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.accessibility.ariaDescription.label', helpKey: 'lowCode.inspector.accessibility.ariaDescription.help', fallbackLabel: 'Accessible description', bindable: true, acceptedSources: ['page', 'component', 'variable'], runtimeConsumer: 'runtime.component.accessibility', accessibility: { role: 'description', descriptionPath: 'props.ariaDescription' } });
    this.property({ path: 'props.tabIndex', section: 'advanced', order: 40, editor: 'number', valueType: 'number', defaultValue: 0, labelKey: 'lowCode.inspector.accessibility.tabIndex.label', helpKey: 'lowCode.inspector.accessibility.tabIndex.help', fallbackLabel: 'Tab index', runtimeConsumer: 'runtime.component.accessibility', validation: { valueType: 'number', integer: true, min: -1, max: 32767 } });
  }
}
