import type {
  ProjectManagementAuditQuery,
  ProjectManagementActivityQuery,
  ProjectManagementMemberCandidateQuery,
  ProjectManagementMyWorkQuery,
  ProjectManagementNotificationQuery,
  ProjectManagementOperationQuery,
  ProjectManagementOverviewQuery,
  ProjectManagementProjectQuery,
  ProjectManagementHomeQuery,
  ProjectManagementRecycleQuery,
  ProjectManagementTaskQuery,
  ProjectManagementWorkspaceQuery,
} from '../../api/project-management/projectManagement.types';
import type { ProjectManagementWorkspaceScope } from '../../features/project-management/state/projectManagementWorkspaceScope';

function root(scope: ProjectManagementWorkspaceScope) {
  return ['astererp', 'project-management', scope.tenantId, scope.appCode] as const;
}

export const projectManagementQueryKeys = {
  all: (scope: ProjectManagementWorkspaceScope) => root(scope),
  activities: (scope: ProjectManagementWorkspaceScope, projectId: string, query: ProjectManagementActivityQuery) => [
    ...root(scope),
    'activities',
    projectId,
    query.pageIndex ?? 1,
    query.pageSize ?? 50,
    query.aggregateType ?? '',
    query.activityType ?? '',
    query.from ?? '',
    query.to ?? '',
  ] as const,
  audit: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementAuditQuery) => [
    ...root(scope),
    'audit',
    query.pageIndex ?? 1,
    query.pageSize ?? 20,
    query.projectId ?? '',
    query.aggregateType ?? '',
    query.activityType ?? '',
    query.keyword ?? '',
    query.from ?? '',
    query.to ?? '',
  ] as const,
  auditDetail: (scope: ProjectManagementWorkspaceScope, id: string) => [...root(scope), 'audit', 'detail', id] as const,
  backups: (scope: ProjectManagementWorkspaceScope) => [...root(scope), 'backups'] as const,
  imConversation: (scope: ProjectManagementWorkspaceScope, projectId: string, taskId?: string) => [
    ...root(scope),
    'im-conversation',
    projectId,
    taskId ?? '',
  ] as const,
  labels: (scope: ProjectManagementWorkspaceScope, projectId: string) => [...root(scope), 'labels', projectId] as const,
  memberCandidates: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementMemberCandidateQuery) => [
    ...root(scope),
    'member-candidates',
    query.pageIndex ?? 1,
    query.pageSize ?? 20,
    query.keyword ?? '',
    query.deptId ?? '',
    query.positionId ?? '',
  ] as const,
  members: (scope: ProjectManagementWorkspaceScope, projectId: string) => [...root(scope), 'members', projectId] as const,
  milestones: (scope: ProjectManagementWorkspaceScope, projectId: string) => [...root(scope), 'milestones', projectId] as const,
  myWork: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementMyWorkQuery) => [
    ...root(scope),
    'my-work',
    query.pageIndex ?? 1,
    query.pageSize ?? 50,
    query.projectId ?? '',
    query.category ?? 'all',
    query.sortBy ?? 'dueDate',
    query.sortDirection ?? 'asc',
    query.includeCompleted ?? false,
  ] as const,
  operations: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementOperationQuery) => [
    ...root(scope),
    'operations',
    query.pageIndex ?? 1,
    query.pageSize ?? 20,
    query.operationType ?? '',
    query.status ?? '',
  ] as const,
  operation: (scope: ProjectManagementWorkspaceScope, operationId: string) => [...root(scope), 'operation', operationId] as const,
  notifications: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementNotificationQuery) => [
    ...root(scope), 'notifications', query.pageIndex ?? 1, query.pageSize ?? 20, query.unreadOnly ?? false, query.notificationType ?? '',
  ] as const,
  overview: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementOverviewQuery) => [
    ...root(scope),
    'overview',
    query.pageIndex ?? 1,
    query.pageSize ?? 20,
    query.projectId ?? '',
    query.keyword ?? '',
  ] as const,
  projects: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementProjectQuery) => [
    ...root(scope),
    'projects',
    query.pageIndex ?? 1,
    query.pageSize ?? 20,
    query.keyword ?? '',
    query.status ?? '',
    query.ownerUserId ?? '',
  ] as const,
  homeProjects: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementHomeQuery) => [
    ...root(scope), 'home', 'projects', JSON.stringify(query),
  ] as const,
  homeProjectsRoot: (scope: ProjectManagementWorkspaceScope) => [...root(scope), 'home', 'projects'] as const,
  homeSummary: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementHomeQuery) => [
    ...root(scope), 'home', 'summary', JSON.stringify(query),
  ] as const,
  homeSummaryRoot: (scope: ProjectManagementWorkspaceScope) => [...root(scope), 'home', 'summary'] as const,
  recycle: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementRecycleQuery) => [
    ...root(scope),
    'recycle',
    query.pageIndex ?? 1,
    query.pageSize ?? 20,
    query.projectId ?? '',
    query.keyword ?? '',
  ] as const,
  reversibleCommands: (scope: ProjectManagementWorkspaceScope) => [...root(scope), 'reversible-commands'] as const,
  savedViews: (scope: ProjectManagementWorkspaceScope, projectId: string) => [...root(scope), 'saved-views', projectId] as const,
  taskAttachments: (scope: ProjectManagementWorkspaceScope, projectId: string, taskId: string) => [
    ...projectManagementQueryKeys.taskAttachmentsProject(scope, projectId),
    taskId,
  ] as const,
  taskAttachmentsProject: (scope: ProjectManagementWorkspaceScope, projectId: string) => [
    ...root(scope),
    'task-attachments',
    projectId,
  ] as const,
  taskComments: (scope: ProjectManagementWorkspaceScope, projectId: string, taskId: string) => [
    ...projectManagementQueryKeys.taskCommentsProject(scope, projectId),
    taskId,
  ] as const,
  taskCommentsProject: (scope: ProjectManagementWorkspaceScope, projectId: string) => [
    ...root(scope),
    'task-comments',
    projectId,
  ] as const,
  taskReminders: (scope: ProjectManagementWorkspaceScope, projectId: string, taskId: string) => [
    ...projectManagementQueryKeys.taskRemindersProject(scope, projectId),
    taskId,
  ] as const,
  taskRemindersProject: (scope: ProjectManagementWorkspaceScope, projectId: string) => [
    ...root(scope),
    'task-reminders',
    projectId,
  ] as const,
  tasks: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementTaskQuery) => [
    ...root(scope),
    'tasks',
    query.projectId,
    query.viewKey ?? 'tree',
    query.pageIndex ?? 1,
    query.pageSize ?? 50,
    query.keyword ?? '',
    query.status ?? '',
    query.assigneeUserId ?? '',
    query.groupBy ?? '',
    query.sortBy ?? 'tree',
    query.sortDirection ?? 'asc',
    query.milestoneId ?? '',
    query.parentTaskId ?? '',
    query.dueFrom ?? '',
    query.dueTo ?? '',
    query.includeCompleted ?? true,
  ] as const,
  tasksProject: (scope: ProjectManagementWorkspaceScope, projectId: string) => [...root(scope), 'tasks', projectId] as const,
  task: (scope: ProjectManagementWorkspaceScope, projectId: string, taskId: string) => [
    ...projectManagementQueryKeys.tasksProject(scope, projectId),
    'detail',
    taskId,
  ] as const,
  workspace: (scope: ProjectManagementWorkspaceScope, query: ProjectManagementWorkspaceQuery) => [
    ...root(scope),
    'workspace',
    query.projectId ?? '',
    query.milestoneId ?? '',
    query.version ?? '',
    query.filter?.keyword ?? '',
    query.filter?.status ?? '',
    query.filter?.assigneeId ?? '',
  ] as const,
};
