import type { ApplicationConnectionDiagnostic } from '../../../api/application-data-center/applicationDataCenter.types';
import { useI18n } from '../../../core/i18n/I18nProvider';

interface ConnectionDiagnosticPanelProps { diagnostic: ApplicationConnectionDiagnostic; }

export function ConnectionDiagnosticPanel({ diagnostic }: ConnectionDiagnosticPanelProps) {
  const { translate: t } = useI18n();
  const statusLabel = diagnostic.success ? t('applicationConsole.dataCenter.diagnostic.passed') : t('applicationConsole.dataCenter.diagnostic.failed');
  return <section className="rounded-md border border-slate-200 bg-white p-3" aria-labelledby="connection-diagnostic-title" aria-live="polite"><div className="flex items-center justify-between gap-2"><h2 id="connection-diagnostic-title" className="text-sm font-semibold text-slate-900">{t('applicationConsole.dataCenter.diagnostic.title')}</h2><span className={diagnostic.success ? 'text-xs font-medium text-emerald-600' : 'text-xs font-medium text-rose-600'}>{statusLabel}</span></div><div className="mt-3 space-y-2" role="list" aria-label={t('applicationConsole.dataCenter.diagnostic.title')}>{diagnostic.stages.map((stage) => <div key={stage.code} className="rounded border border-slate-100 bg-slate-50 px-3 py-2" role="listitem" aria-label={t('applicationConsole.dataCenter.diagnostic.stage').replace('{code}', stage.code).replace('{status}', stage.status).replace('{message}', stage.message).replace('{duration}', `${stage.durationMs} ms`)}><div className="flex items-center justify-between gap-2 text-xs"><span className="font-medium text-slate-800">{stage.code}</span><span className={stage.status === 'Passed' || stage.status === 'NotApplicable' ? 'text-emerald-600' : stage.status === 'Blocked' ? 'text-amber-600' : 'text-rose-600'}>{stage.status} · {stage.durationMs} ms</span></div><div className="mt-1 text-xs leading-5 text-slate-600">{stage.message}</div>{stage.repairSuggestion ? <div className="mt-1 text-xs leading-5 text-amber-700">{t('applicationConsole.dataCenter.diagnostic.repairSuggestion').replace('{suggestion}', stage.repairSuggestion)}</div> : null}{stage.detailJson ? <pre className="mt-2 max-h-24 overflow-auto rounded bg-slate-900 p-2 text-[11px] text-slate-100" aria-label={`${stage.code} detail`}>{stage.detailJson}</pre> : null}</div>)}</div></section>;
}
