import type { projectManagementOperationsMessagesZhCN } from '../zh-CN/projectManagementOperations';

export const projectManagementOperationsMessagesEnUS = {
  'projectManagement.operation.retry': 'Retry',
  'projectManagement.operation.loading': 'Loading…',
  'projectManagement.operation.loadFailed': 'Could not load data',
  'projectManagement.operation.unknownError': 'The operation failed. Try again later.'
  ,'projectManagement.notification.title': 'Project notifications', 'projectManagement.notification.all': 'All', 'projectManagement.notification.unread': 'Unread', 'projectManagement.notification.markAllRead': 'Mark all read', 'projectManagement.notification.markRead': 'Mark read', 'projectManagement.notification.typeAria': 'Notification type', 'projectManagement.notification.unavailable': 'The related item is unavailable', 'projectManagement.notification.markAllFailed': 'Could not mark all notifications as read', 'projectManagement.notification.markReadFailed': 'Could not mark notification as read', 'projectManagement.notification.openFailed': 'Could not open notification', 'projectManagement.notification.realtimeUnavailable': 'Real-time connection is unavailable. Notifications remain in the app and refresh when the connection returns.', 'projectManagement.notification.enableBrowser': 'Enable task and high-priority notifications', 'projectManagement.notification.browserDenied': 'Browser notifications are denied; only in-app notifications will be shown.', 'projectManagement.notification.loading': 'Loading notifications…', 'projectManagement.notification.loadFailed': 'Could not load notifications.', 'projectManagement.notification.empty': 'No project notifications', 'projectManagement.notification.countOverflow': '99+',
  'projectManagement.notification.type.all': 'All types', 'projectManagement.notification.type.taskReminder': 'Task reminder', 'projectManagement.notification.type.mentioned': 'Mention', 'projectManagement.notification.type.assigned': 'Task assigned', 'projectManagement.notification.type.participantAdded': 'Participant added', 'projectManagement.notification.type.participantRemoved': 'Participant removed', 'projectManagement.notification.type.statusChanged': 'Task status', 'projectManagement.notification.type.dueDateChanged': 'Due date', 'projectManagement.notification.type.milestoneRisk': 'Milestone risk', 'projectManagement.notification.type.excelImport': 'Excel import', 'projectManagement.notification.type.syncExport': 'Sync export', 'projectManagement.notification.type.syncImport': 'Sync import', 'projectManagement.notification.type.succeeded': 'Operation completed', 'projectManagement.notification.type.failed': 'Operation failed'
  ,'projectManagement.api.notification.open.auditDenied': 'You do not have permission to view the related operation.', 'projectManagement.api.notification.open.syncDenied': 'You do not have permission to view project synchronization.', 'projectManagement.api.notification.open.unavailable': 'This notification is not associated with an available project object.', 'projectManagement.api.notification.open.targetUnavailable': 'The related project or task was deleted, or you no longer have access.'
} satisfies Record<keyof typeof projectManagementOperationsMessagesZhCN, string>;
