import type { projectManagementCollaborationMessagesZhCN } from '../zh-CN/projectManagementCollaboration';

export const projectManagementCollaborationMessagesEnUS = {
  'projectManagement.editor.create': 'New task', 'projectManagement.editor.edit': 'Edit task', 'projectManagement.editor.titleAria': 'Task title', 'projectManagement.editor.titlePlaceholder': 'Enter a task title', 'projectManagement.editor.descriptionAria': 'Task description', 'projectManagement.editor.descriptionPlaceholder': 'Describe the background, goal, and acceptance criteria. Type @ to mention project members.',
  'projectManagement.editor.continueCreating': 'Create another after saving', 'projectManagement.editor.cancel': 'Cancel', 'projectManagement.editor.save': 'Save', 'projectManagement.editor.savedCreate': 'Task created', 'projectManagement.editor.savedUpdate': 'Task updated', 'projectManagement.editor.saveFailed': 'Could not save task', 'projectManagement.editor.conflict': 'A concurrent update was detected. Your local draft is preserved.',
  'projectManagement.editor.closeTitle': 'Close task editor', 'projectManagement.editor.closeDescription': 'There are unsaved changes or draft attachments. Discard this edit?', 'projectManagement.editor.discard': 'Discard changes',
  'projectManagement.editor.attachment': 'Attachments', 'projectManagement.editor.upload': 'Upload attachment', 'projectManagement.editor.uploaded': 'Attachment uploaded', 'projectManagement.editor.uploadFailed': 'Could not upload attachment. The draft is preserved.',
  'projectManagement.editor.comment': 'Comments', 'projectManagement.editor.commentAria': 'New comment', 'projectManagement.editor.commentPlaceholder': 'Add a comment. Type @ to mention a member.', 'projectManagement.editor.publishComment': 'Post comment', 'projectManagement.editor.commentPublished': 'Comment posted', 'projectManagement.editor.afterSaveHint': 'Save the task before adding comments or followers.',
  'projectManagement.editor.field.project': 'Project', 'projectManagement.editor.field.workItemType': 'Work item type', 'projectManagement.editor.field.status': 'Status', 'projectManagement.editor.field.assignee': 'Assignee', 'projectManagement.editor.field.parent': 'Parent work item', 'projectManagement.editor.field.milestone': 'Milestone', 'projectManagement.editor.field.startDate': 'Start date', 'projectManagement.editor.field.dueDate': 'Due date', 'projectManagement.editor.field.priority': 'Priority', 'projectManagement.editor.field.risk': 'Risk', 'projectManagement.editor.field.requirementType': 'Task type', 'projectManagement.editor.field.requirementSource': 'Task source', 'projectManagement.editor.field.followers': 'Followers',
  'projectManagement.editor.currentProject': 'Current project', 'projectManagement.editor.conflictDetected': 'A concurrent update was detected. Your local draft is preserved.', 'projectManagement.editor.server': 'Server', 'projectManagement.editor.local': 'Local', 'projectManagement.editor.reload': 'Load server values', 'projectManagement.editor.keepLocal': 'Keep local draft', 'projectManagement.editor.overwrite': 'Overwrite and save'
  ,'projectManagement.richEditor.loading': 'Loading editor…', 'projectManagement.richEditor.toolbar': 'Rich-text toolbar', 'projectManagement.richEditor.paragraph': 'Paragraph', 'projectManagement.richEditor.heading': 'Heading', 'projectManagement.richEditor.bold': 'Bold', 'projectManagement.richEditor.italic': 'Italic', 'projectManagement.richEditor.strike': 'Strikethrough', 'projectManagement.richEditor.bulletList': 'Bulleted list', 'projectManagement.richEditor.orderedList': 'Numbered list', 'projectManagement.richEditor.quote': 'Quote', 'projectManagement.richEditor.link': 'Link', 'projectManagement.richEditor.linkPrompt': 'Link address', 'projectManagement.richEditor.mention': 'Mention member', 'projectManagement.richEditor.undo': 'Undo', 'projectManagement.richEditor.redo': 'Redo', 'projectManagement.richEditor.placeholder': 'Enter content', 'projectManagement.richEditor.searchMembers': 'Searching members…', 'projectManagement.richEditor.noMembers': 'No matching project members'
} satisfies Record<keyof typeof projectManagementCollaborationMessagesZhCN, string>;
