import type { projectManagementWorkItemsMessagesZhCN } from '../zh-CN/projectManagementWorkItems';

export const projectManagementWorkItemsMessagesEnUS = {
  'projectManagement.workItems.view.tree': 'Tree', 'projectManagement.workItems.view.flat': 'List', 'projectManagement.workItems.view.card': 'Cards', 'projectManagement.workItems.view.board': 'Board', 'projectManagement.workItems.view.gantt': 'Gantt', 'projectManagement.workItems.view.calendar': 'Calendar',
  'projectManagement.workItems.refresh': 'Refresh', 'projectManagement.workItems.column.progress': 'Progress', 'projectManagement.workItems.notifications': 'Notifications',
  'projectManagement.enum.status.Backlog': 'Backlog',
  'projectManagement.workItems.segment.all': 'All tasks', 'projectManagement.workItems.segment.mine': 'My tasks', 'projectManagement.workItems.segment.inProgress': 'In progress', 'projectManagement.workItems.segment.todo': 'Pending', 'projectManagement.workItems.segment.done': 'Completed', 'projectManagement.workItems.segment.closed': 'Closed',
  'projectManagement.workItems.searchAria': 'Search tasks', 'projectManagement.workItems.searchPlaceholder': 'Search by code or title', 'projectManagement.workItems.filter': 'Filter', 'projectManagement.workItems.view': 'Views', 'projectManagement.workItems.type': 'Task type', 'projectManagement.workItems.risk': 'Risk', 'projectManagement.workItems.all': 'All',
  'projectManagement.workItems.type.feature': 'Feature', 'projectManagement.workItems.type.nonFunctional': 'Non-functional', 'projectManagement.workItems.type.other': 'Other', 'projectManagement.workItems.risk.none': 'No risk',
  'projectManagement.workItems.saveViewAria': 'View name', 'projectManagement.workItems.saveViewPlaceholder': 'Enter a view name', 'projectManagement.workItems.saveView': 'Save current view', 'projectManagement.workItems.saved': 'View saved', 'projectManagement.workItems.saveFailed': 'Could not save view', 'projectManagement.workItems.savedInvalid': 'Saved view is invalid',
  'projectManagement.workItems.statusRollback': 'The status update failed and was reverted.', 'projectManagement.workItems.conflictRefresh': 'The task was updated by someone else. The list was refreshed — please drag again.', 'projectManagement.workItems.loadFailed': 'Could not load tasks', 'projectManagement.workItems.retry': 'Retry', 'projectManagement.workItems.empty': 'No tasks', 'projectManagement.workItems.boardEmpty': 'Drop tasks here',
  'projectManagement.workItems.column.code': 'Code', 'projectManagement.workItems.column.title': 'Title', 'projectManagement.workItems.column.status': 'Status', 'projectManagement.workItems.column.assignee': 'Assignee', 'projectManagement.workItems.column.priority': 'Priority', 'projectManagement.workItems.column.parent': 'Parent work item', 'projectManagement.workItems.column.type': 'Task type', 'projectManagement.workItems.column.points': 'Story points',
  'projectManagement.workItems.expandCollapse': 'Expand or collapse {title}', 'projectManagement.workItems.unassigned': 'Unassigned', 'projectManagement.workItems.children': 'Children {completed}/{total} · {points} pts',
  'projectManagement.enum.status.Todo': 'Pending', 'projectManagement.enum.status.InProgress': 'In progress', 'projectManagement.enum.status.Blocked': 'Blocked', 'projectManagement.enum.status.Done': 'Completed', 'projectManagement.enum.status.Closed': 'Closed',
  'projectManagement.enum.priority.Low': 'Low', 'projectManagement.enum.priority.Medium': 'Medium', 'projectManagement.enum.priority.High': 'High', 'projectManagement.enum.priority.Urgent': 'Urgent',
  'projectManagement.enum.status.Planned': 'Planned', 'projectManagement.enum.status.Active': 'Active', 'projectManagement.enum.status.Completed': 'Completed', 'projectManagement.enum.status.Archived': 'Archived', 'projectManagement.enum.status.Paused': 'Paused', 'projectManagement.enum.status.Cancelled': 'Cancelled',
  'projectManagement.enum.workItemType.Requirement': 'Task', 'projectManagement.enum.workItemType.UserStory': 'User story', 'projectManagement.enum.workItemType.Task': 'Sub-task', 'projectManagement.enum.workItemType.Bug': 'Bug',
  'projectManagement.enum.risk.None': 'None', 'projectManagement.enum.risk.Low': 'Low', 'projectManagement.enum.risk.Medium': 'Medium', 'projectManagement.enum.risk.High': 'High',
  'projectManagement.enum.requirementType.Feature': 'Feature', 'projectManagement.enum.requirementType.NonFunctional': 'Non-functional', 'projectManagement.enum.requirementType.Other': 'Other',
  'projectManagement.enum.requirementSource.ProductPlan': 'Product plan', 'projectManagement.enum.requirementSource.Customer': 'Customer', 'projectManagement.enum.requirementSource.Internal': 'Internal', 'projectManagement.enum.requirementSource.BugConversion': 'Bug to task', 'projectManagement.enum.requirementSource.Other': 'Other'
} satisfies Record<keyof typeof projectManagementWorkItemsMessagesZhCN, string>;
