import type { ReactNode } from 'react';

import { createConversionPipeline } from '../binding/conversionPipeline';
import { ResourceExplorer } from '../binding/ResourceExplorer';

import { getExpressionFunction, listExpressionFunctions } from './expressionFunctionCatalog';
import type { ExpressionGraph, ExpressionNode } from './expressionGraph';
import { appendExpressionArgument, createExpressionNode, deleteExpressionNode, expressionNodeAt, moveExpressionArgument, replaceExpressionNode, type ExpressionPath } from './expressionGraphEditorModel';
import type { BindingDocument, DesignerValueType } from './expressionTypes';

export interface ExpressionNodeEditorProps { document?: BindingDocument | null; expectedType: DesignerValueType; graph: ExpressionGraph; path: ExpressionPath; onChange: (graph: ExpressionGraph) => void }

export function ExpressionNodeEditor({ document, expectedType, graph, path, onChange }: ExpressionNodeEditorProps) {
  const node = expressionNodeAt(graph, path);
  if (!node) return <p className="rounded border border-dashed border-rose-300 p-2 text-xs text-rose-700" data-testid="expression-missing-node">Missing expression node at {pathLabel(path)}.</p>;
  const update = (replacement: ExpressionNode | null) => onChange(replaceExpressionNode(graph, path, replacement));
  return <section className="rounded border border-slate-200 bg-slate-50 p-2" data-testid={`expression-node-${pathLabel(path)}`}><div className="flex flex-wrap items-center gap-1"><span className="mr-auto text-[10px] font-semibold text-slate-600">{pathLabel(path)}</span><span className={`rounded px-1 text-[10px] ${node.valueType === expectedType || expectedType === 'json' ? 'bg-slate-200 text-slate-600' : 'bg-amber-100 text-amber-700'}`} data-testid="expression-type-hint">{node.valueType}</span><select aria-label={`Replace node ${pathLabel(path)}`} value={node.kind} onChange={(event) => update(createExpressionNode(event.target.value as ExpressionNode['kind'], node.valueType))} className="rounded border border-slate-300 bg-white px-1 text-[10px]">{['literal', 'resourceRef', 'functionCall', 'conversion', 'condition', 'logic', 'object', 'array', 'template', 'defaultValue'].map((kind) => <option key={kind} value={kind}>{kind}</option>)}</select><button type="button" aria-label={`Delete node ${pathLabel(path)}`} className="rounded border border-rose-200 px-1 text-[10px] text-rose-700" onClick={() => onChange(deleteExpressionNode(graph, path))}>Delete</button></div>
    {node.kind === 'literal' ? <LiteralEditor node={node} onChange={(value) => update({ ...node, value })} /> : null}
    {node.kind === 'resourceRef' ? <div className="mt-2 space-y-1"><p className="text-[10px] text-slate-500">Resource id: {node.resourceId || 'unselected'}</p><ResourceExplorer document={document} expectedType={node.valueType} onSelect={(resource) => update({ ...node, resourceId: resource.id, valueType: resource.valueType })} /></div> : null}
    {node.kind === 'conversion' ? <div className="mt-2 space-y-1"><label className="block text-[10px] text-slate-600">Conversion<select aria-label="Conversion" value={node.pipeline[0]?.name ?? ''} onChange={(event) => update({ ...node, pipeline: createConversionPipeline(node.input.valueType, node.valueType).steps.map((step) => ({ ...step, name: event.target.value })) })} className="ml-1 rounded border border-slate-300 bg-white px-1 text-xs"><option value="">Select conversion</option>{createConversionPipeline(node.input.valueType, node.valueType).steps.map((step) => <option key={step.name} value={step.name}>{step.name}</option>)}</select></label><ExpressionNodeEditor document={document} expectedType={node.input.valueType} graph={graph} path={[...path, 'input']} onChange={onChange} /></div> : null}
    {node.kind === 'condition' ? <div className="mt-2 space-y-1"><NodeSlot label="When" document={document} expectedType="boolean" graph={graph} path={[...path, 'when']} onChange={onChange} /><NodeSlot label="Then" document={document} expectedType={node.valueType} graph={graph} path={[...path, 'then']} onChange={onChange} /><NodeSlot label="Otherwise" document={document} expectedType={node.valueType} graph={graph} path={[...path, 'otherwise']} onChange={onChange} /></div> : null}
    {node.kind === 'defaultValue' ? <div className="mt-2 space-y-1"><NodeSlot label="Input" document={document} expectedType={node.valueType} graph={graph} path={[...path, 'input']} onChange={onChange} /><label className="block text-[10px] text-slate-600">Fallback<input aria-label="Default fallback" value={String(node.fallback ?? '')} onChange={(event) => update({ ...node, fallback: parseValue(event.target.value, node.valueType) })} className="ml-1 rounded border border-slate-300 bg-white px-1 text-xs" /></label></div> : null}
    {node.kind === 'logic' ? <ArgumentEditor graph={graph} path={path} node={node} document={document} expectedType="boolean" onChange={onChange} operator={<select aria-label="Logic operator" value={node.operator} onChange={(event) => update({ ...node, operator: event.target.value as typeof node.operator })} className="rounded border border-slate-300 bg-white px-1 text-xs"><option value="and">and</option><option value="or">or</option><option value="not">not</option></select>} /> : null}
    {node.kind === 'functionCall' ? <ArgumentEditor graph={graph} path={path} node={node} document={document} expectedType={node.valueType} onChange={onChange} operator={<select aria-label="Function" value={node.functionId} onChange={(event) => { const definition = getExpressionFunction(event.target.value); const args = Array.from({ length: definition?.minArgs ?? 1 }, (_, index) => createExpressionNode('literal', argumentValueType(definition?.argumentTypes[index], node.valueType))); update({ ...node, functionId: event.target.value, args, valueType: definition?.returnType === 'sameAsFirst' ? args[0]?.valueType ?? node.valueType : definition?.returnType ?? node.valueType }); }} className="rounded border border-slate-300 bg-white px-1 text-xs"><option value="">Select function</option>{listExpressionFunctions().map((definition) => <option key={definition.name} value={definition.name}>{definition.label}</option>)}</select>} /> : null}
    {node.kind === 'object' ? <p className="mt-2 text-xs text-slate-500">Object properties: {Object.keys(node.properties).length}. Add properties through the AST import.</p> : null}
    {node.kind === 'array' || node.kind === 'template' ? <p className="mt-2 text-xs text-slate-500">Items: {node.items.length}. Add items through the AST import.</p> : null}
  </section>;
}

function LiteralEditor({ node, onChange }: { node: Extract<ExpressionNode, { kind: 'literal' }>; onChange: (value: unknown) => void }) { return <label className="mt-2 block text-[10px] text-slate-600">Value<input aria-label="Literal value" value={node.value == null ? '' : String(node.value)} onChange={(event) => onChange(parseValue(event.target.value, node.valueType))} className="ml-1 rounded border border-slate-300 bg-white px-1 text-xs" /></label>; }
function NodeSlot({ label, document, expectedType, graph, path, onChange }: { label: string; document?: BindingDocument | null; expectedType: DesignerValueType; graph: ExpressionGraph; path: ExpressionPath; onChange: (graph: ExpressionGraph) => void }) { return <div className="rounded border border-slate-200 bg-white p-1"><p className="text-[10px] text-slate-500">{label}</p><ExpressionNodeEditor document={document} expectedType={expectedType} graph={graph} path={path} onChange={onChange} /></div>; }
function ArgumentEditor({ graph, path, node, document, expectedType, onChange, operator }: { graph: ExpressionGraph; path: ExpressionPath; node: Extract<ExpressionNode, { kind: 'functionCall' | 'logic' }>; document?: BindingDocument | null; expectedType: DesignerValueType; onChange: (graph: ExpressionGraph) => void; operator: ReactNode }) { const definition = node.kind === 'functionCall' ? getExpressionFunction(node.functionId) : undefined; return <div className="mt-2 space-y-1"><div className="flex items-center gap-1"><span className="text-[10px] text-slate-600">{node.kind === 'functionCall' ? 'Function' : 'Operator'}</span>{operator}<button type="button" aria-label="Add argument" onClick={() => onChange(appendExpressionArgument(graph, path))}>+ arg</button></div>{node.args.map((_, index) => <div key={`${pathLabel(path)}-${index}`} className="rounded border border-slate-200 bg-white p-1"><div className="flex items-center gap-1"><span className="mr-auto text-[10px] text-slate-500">{definition?.argumentLabels[index] ?? `Argument ${index + 1}`}</span><button type="button" aria-label={`Move argument ${index} up`} disabled={index === 0} onClick={() => onChange(moveExpressionArgument(graph, path, index, -1))}>↑</button><button type="button" aria-label={`Move argument ${index} down`} disabled={index === node.args.length - 1} onClick={() => onChange(moveExpressionArgument(graph, path, index, 1))}>↓</button><button type="button" aria-label={`Remove argument ${index}`} onClick={() => onChange(replaceExpressionNode(graph, path, { ...node, args: node.args.filter((_, itemIndex) => itemIndex !== index) }))}>×</button></div><ExpressionNodeEditor document={document} expectedType={expectedType} graph={graph} path={[...path, { args: index }]} onChange={onChange} /></div>)}</div>; }
function argumentValueType(type: string | undefined, fallback: DesignerValueType): DesignerValueType { return !type || type === 'any' || type === 'sameAsFirst' ? fallback : type as DesignerValueType; }
function parseValue(value: string, valueType: DesignerValueType): unknown { if (valueType === 'number') return value === '' ? 0 : Number(value); if (valueType === 'boolean') return value === 'true'; if (valueType === 'array' || valueType === 'object' || valueType === 'json') { try { return JSON.parse(value); } catch { return value; } } return value; }
function pathLabel(path: ExpressionPath): string { return path.slice(1).reduce<string>((label, segment) => `${label}.${typeof segment === 'object' ? ('args' in segment ? `args[${segment.args}]` : `property:${segment.property}`) : segment}`, 'root'); }
