import { DataComponentInspectorDefinitionBase } from '../base/DataComponentInspectorDefinitionBase';

export class ChartBasicInspectorDefinition extends DataComponentInspectorDefinitionBase {
  public constructor() {
    super('chart.basic');
    this.property({ path: 'props.title', section: 'content', order: 10, editor: 'text', valueType: 'string', defaultValue: 'Chart', labelKey: 'lowCode.inspector.chart.title.label', helpKey: 'lowCode.inspector.chart.title.help', fallbackLabel: 'Title', runtimeConsumer: 'runtime.component.props.title' });
    this.property({ path: 'props.chartType', section: 'content', order: 20, editor: 'select', valueType: 'string', defaultValue: 'bar', labelKey: 'lowCode.inspector.chart.type.label', helpKey: 'lowCode.inspector.chart.type.help', fallbackLabel: 'Chart type', runtimeConsumer: 'runtime.chart.type', options: [{ label: 'Bar', value: 'bar' }, { label: 'Column', value: 'column' }, { label: 'Line', value: 'line' }, { label: 'Area', value: 'area' }, { label: 'Pie', value: 'pie' }] });
    this.property({ path: 'props.axis', section: 'data', order: 30, editor: 'json', valueType: 'object', defaultValue: { xKey: 'label', yKey: 'value' }, labelKey: 'lowCode.inspector.chart.axis.label', helpKey: 'lowCode.inspector.chart.axis.help', fallbackLabel: 'Axes', bindable: true, acceptedSources: ['page', 'component', 'variable', 'dataset'], runtimeConsumer: 'runtime.chart.axis' });
    this.property({ path: 'props.series', section: 'data', order: 40, editor: 'json', valueType: 'array', defaultValue: [], labelKey: 'lowCode.inspector.chart.series.label', helpKey: 'lowCode.inspector.chart.series.help', fallbackLabel: 'Series', bindable: true, acceptedSources: ['page', 'component', 'variable', 'dataset'], runtimeConsumer: 'runtime.chart.series' });
    this.property({ path: 'props.legend', section: 'appearance', order: 10, editor: 'boolean', valueType: 'boolean', defaultValue: true, labelKey: 'lowCode.inspector.chart.legend.label', helpKey: 'lowCode.inspector.chart.legend.help', fallbackLabel: 'Legend', runtimeConsumer: 'runtime.chart.legend' });
    this.property({ path: 'props.tooltip', section: 'appearance', order: 20, editor: 'boolean', valueType: 'boolean', defaultValue: true, labelKey: 'lowCode.inspector.chart.tooltip.label', helpKey: 'lowCode.inspector.chart.tooltip.help', fallbackLabel: 'Tooltip', runtimeConsumer: 'runtime.chart.tooltip' });
    this.property({ path: 'props.loadingState', section: 'content', order: 50, editor: 'text', valueType: 'string', defaultValue: 'Loading', labelKey: 'lowCode.inspector.chart.loadingState.label', helpKey: 'lowCode.inspector.chart.loadingState.help', fallbackLabel: 'Loading state', runtimeConsumer: 'runtime.chart.loadingState' });
    this.property({ path: 'props.errorState', section: 'content', order: 60, editor: 'text', valueType: 'string', defaultValue: 'Unable to load chart data', labelKey: 'lowCode.inspector.chart.errorState.label', helpKey: 'lowCode.inspector.chart.errorState.help', fallbackLabel: 'Error state', runtimeConsumer: 'runtime.chart.errorState' });
    this.property({ path: 'props.emptyState', section: 'content', order: 70, editor: 'text', valueType: 'string', defaultValue: 'No chart data', labelKey: 'lowCode.inspector.chart.emptyState.label', helpKey: 'lowCode.inspector.chart.emptyState.help', fallbackLabel: 'Empty state', runtimeConsumer: 'runtime.chart.emptyState' });
  }
}
