import { TableInspectorDefinitionBase } from '../base/TableInspectorDefinitionBase';

export class ReportDataTableInspectorDefinition extends TableInspectorDefinitionBase {
  public constructor() {
    super('report.dataTable');
    this.property({ path: 'props.title', section: 'content', order: 10, editor: 'text', valueType: 'string', defaultValue: '', labelKey: 'lowCode.inspector.table.title.label', helpKey: 'lowCode.inspector.table.title.help', fallbackLabel: 'Title', runtimeConsumer: 'runtime.component.props.title' });
    this.property({ path: 'props.loadingState', section: 'content', order: 20, editor: 'text', valueType: 'string', defaultValue: 'Loading…', labelKey: 'lowCode.inspector.table.loadingState.label', helpKey: 'lowCode.inspector.table.loadingState.help', fallbackLabel: 'Loading state', runtimeConsumer: 'runtime.table.loadingState' });
    this.property({ path: 'props.emptyState', section: 'content', order: 30, editor: 'text', valueType: 'string', defaultValue: '暂无数据', labelKey: 'lowCode.inspector.table.emptyState.label', helpKey: 'lowCode.inspector.table.emptyState.help', fallbackLabel: 'Empty state', runtimeConsumer: 'runtime.table.emptyState' });
    this.property({ path: 'props.pageSize', section: 'data', order: 50, editor: 'number', valueType: 'number', defaultValue: 20, labelKey: 'lowCode.inspector.table.pageSize.label', helpKey: 'lowCode.inspector.table.pageSize.help', fallbackLabel: 'Page size', validation: { valueType: 'number', integer: true, min: 1, max: 200 }, runtimeConsumer: 'runtime.table.pageSize' });
    this.property({ path: 'props.rowActions', section: 'interaction', order: 10, editor: 'json', valueType: 'array', defaultValue: [], labelKey: 'lowCode.inspector.table.rowActions.label', helpKey: 'lowCode.inspector.table.rowActions.help', fallbackLabel: 'Row actions', bindable: true, acceptedSources: ['page', 'component', 'variable', 'dataset'], runtimeConsumer: 'runtime.table.rowActions' });
    this.property({ path: 'props.editable', section: 'interaction', order: 20, editor: 'boolean', valueType: 'boolean', defaultValue: false, labelKey: 'lowCode.inspector.table.editable.label', helpKey: 'lowCode.inspector.table.editable.help', fallbackLabel: 'Editable', runtimeConsumer: 'runtime.table.editing' });
    this.property({ path: 'props.commitOnBlur', section: 'interaction', order: 30, editor: 'boolean', valueType: 'boolean', defaultValue: true, labelKey: 'lowCode.inspector.table.commitOnBlur.label', helpKey: 'lowCode.inspector.table.commitOnBlur.help', fallbackLabel: 'Commit on blur', runtimeConsumer: 'runtime.table.editing' });
    this.property({ path: 'props.editing', section: 'interaction', order: 40, editor: 'json', valueType: 'object', defaultValue: {}, labelKey: 'lowCode.inspector.table.editingConfig.label', helpKey: 'lowCode.inspector.table.editingConfig.help', fallbackLabel: 'Editing configuration', runtimeConsumer: 'runtime.table.editing' });
    this.property({ path: 'props.keyField', section: 'data', order: 60, editor: 'text', valueType: 'string', defaultValue: 'id', labelKey: 'lowCode.inspector.table.keyField.label', helpKey: 'lowCode.inspector.table.keyField.help', fallbackLabel: 'Key field', runtimeConsumer: 'runtime.table.editing' });
    this.property({ path: 'props.editPermissionGranted', section: 'interaction', order: 50, editor: 'boolean', valueType: 'boolean', defaultValue: true, labelKey: 'lowCode.inspector.table.editPermission.label', helpKey: 'lowCode.inspector.table.editPermission.help', fallbackLabel: 'Edit permission granted', runtimeConsumer: 'runtime.table.editing' });
  }
}
