using SharedPermissionCodes = AsterERP.Shared.PermissionCodes;

namespace AsterERP.Api.Application.ApplicationConsole;

public static class ApplicationShellPermissionCatalog
{
    public static readonly IReadOnlyList<ApplicationShellPermissionDefinition> Definitions =
    [
        new("ApplicationConsole", SharedPermissionCodes.AppHomeView, "首页访问"),
        new("ApplicationConsole", SharedPermissionCodes.AppConsoleView, "应用控制台访问"),
        new("ApplicationConsole", SharedPermissionCodes.AppWorkbenchView, "工作台访问"),
        new("ApplicationConsole", SharedPermissionCodes.AppApplicationCenterView, "应用中心访问"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterView, "开发中心访问"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterBusinessObjectView, "业务对象构建工作台访问"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterDesignerView, "完整低代码设计器查看"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterDesignerEdit, "完整低代码设计器编辑"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterDesignerDelete, "完整低代码设计器删除页面"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterDesignerPreview, "完整低代码设计器预览"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterDesignerPublish, "完整低代码设计器发布"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterDesignerPermissionEdit, "完整低代码设计器权限配置"),
        new("ApplicationConsole", SharedPermissionCodes.AppDevelopmentCenterMonitoringWrite, "开发中心可观测事件写入"),
        new("ApplicationConsole", SharedPermissionCodes.AppDataCenterView, "数据中心访问"),
        .. ApplicationDataCenterPermissionDefinitionCatalog.Definitions,

        new("ProjectManagement", SharedPermissionCodes.ProjectManagementProjectView, "项目中心访问"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementProjectAdd, "项目新增"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementProjectEdit, "项目编辑"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementProjectArchive, "项目归档"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementProjectDelete, "项目删除"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementProjectRestore, "项目恢复"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementProjectPurge, "项目永久删除"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementMemberView, "项目成员查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementMemberManage, "项目成员管理"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementMilestoneView, "里程碑查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementMilestoneManage, "里程碑管理"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskView, "任务查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskAdd, "任务新增"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskEdit, "任务编辑"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskDelete, "任务删除"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskRestore, "任务恢复"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskMove, "任务移动"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskAssign, "任务分配"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskManageDependency, "任务依赖管理"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskOverrideWip, "任务 WIP 强制绕过"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementLabelView, "标签查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementLabelManage, "标签管理"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementTaskTemplateManage, "任务模板管理"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementCommentView, "评论查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementCommentAdd, "评论新增"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementNotificationView, "项目通知查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementImConversationView, "项目关联 IM 会话查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementImConversationManage, "项目关联 IM 会话管理"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementAttachmentManage, "附件管理"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementReportExport, "项目报表导出"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementSyncImport, "项目同步导入"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementSyncExport, "项目同步导出"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementBackupManage, "项目数据备份恢复"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementAuditView, "项目审计查看"),
        new("ProjectManagement", SharedPermissionCodes.ProjectManagementAuditExport, "项目审计导出"),

        new("IM", SharedPermissionCodes.ImConversationView, "IM 会话查看"),
        new("IM", SharedPermissionCodes.ImConversationCreate, "IM 会话创建"),
        new("IM", SharedPermissionCodes.ImMessageSend, "IM 消息发送"),
        new("IM", SharedPermissionCodes.ImMessageRead, "IM 消息读取"),
        new("IM", SharedPermissionCodes.ImUserSearch, "IM 用户搜索"),

        new("Workflow", SharedPermissionCodes.WorkflowModelQuery, "流程模型查询"),
        new("Workflow", SharedPermissionCodes.WorkflowModelAdd, "流程模型新增"),
        new("Workflow", SharedPermissionCodes.WorkflowModelEdit, "流程模型编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowModelDelete, "流程模型删除"),
        new("Workflow", SharedPermissionCodes.WorkflowModelPublish, "流程模型发布"),
        new("Workflow", SharedPermissionCodes.WorkflowModelSuspend, "流程模型停用"),
        new("Workflow", SharedPermissionCodes.WorkflowDeploymentQuery, "流程定义查询"),
        new("Workflow", SharedPermissionCodes.WorkflowDeploymentResource, "流程定义资源"),
        new("Workflow", SharedPermissionCodes.WorkflowBindingQuery, "审批配置查询"),
        new("Workflow", SharedPermissionCodes.WorkflowBindingEdit, "审批配置编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowBindingDelete, "审批配置删除"),
        new("Workflow", SharedPermissionCodes.WorkflowFormQuery, "审批表单资源查询"),
        new("Workflow", SharedPermissionCodes.WorkflowDraftQuery, "审批草稿查询"),
        new("Workflow", SharedPermissionCodes.WorkflowDraftEdit, "审批草稿编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowDraftDelete, "审批草稿删除"),
        new("Workflow", SharedPermissionCodes.WorkflowDraftSubmit, "审批草稿提交"),
        new("Workflow", SharedPermissionCodes.WorkflowCategoryQuery, "流程分类查询"),
        new("Workflow", SharedPermissionCodes.WorkflowCategoryEdit, "流程分类编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowCategoryDelete, "流程分类删除"),
        new("Workflow", SharedPermissionCodes.WorkflowInstanceQuery, "审批实例查询"),
        new("Workflow", SharedPermissionCodes.WorkflowInstanceStart, "运行时发起审批"),
        new("Workflow", SharedPermissionCodes.WorkflowInstanceWithdraw, "审批实例撤回"),
        new("Workflow", SharedPermissionCodes.WorkflowInstanceTerminate, "审批实例终止"),
        new("Workflow", SharedPermissionCodes.WorkflowInstanceVariable, "审批实例变量"),
        new("Workflow", SharedPermissionCodes.WorkflowTaskQuery, "审批任务查询"),
        new("Workflow", SharedPermissionCodes.WorkflowTaskClaim, "审批任务认领"),
        new("Workflow", SharedPermissionCodes.WorkflowTaskApprove, "审批任务办理"),
        new("Workflow", SharedPermissionCodes.WorkflowTaskTransfer, "审批任务转办"),
        new("Workflow", SharedPermissionCodes.WorkflowTaskDelegate, "审批任务委派"),
        new("Workflow", SharedPermissionCodes.WorkflowTaskAttachment, "审批任务附件"),
        new("Workflow", SharedPermissionCodes.WorkflowTaskComment, "审批任务评论"),
        new("Workflow", SharedPermissionCodes.WorkflowHistoryQuery, "审批历史查询"),
        new("Workflow", SharedPermissionCodes.WorkflowReportQuery, "审批报表查询"),
        new("Workflow", SharedPermissionCodes.WorkflowParticipantQuery, "审批参与人查询"),
        new("Workflow", SharedPermissionCodes.WorkflowDelegationQuery, "审批委托查询"),
        new("Workflow", SharedPermissionCodes.WorkflowDelegationEdit, "审批委托编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowDelegationDelete, "审批委托删除"),
        new("Workflow", SharedPermissionCodes.WorkflowCalendarQuery, "审批工作日历查询"),
        new("Workflow", SharedPermissionCodes.WorkflowCalendarEdit, "审批工作日历编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowCalendarDelete, "审批工作日历删除"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationChannelQuery, "审批通知渠道查询"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationChannelEdit, "审批通知渠道编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationChannelDelete, "审批通知渠道删除"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationTemplateQuery, "审批通知模板查询"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationTemplateEdit, "审批通知模板编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationTemplateDelete, "审批通知模板删除"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationRuleQuery, "审批通知规则查询"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationRuleEdit, "审批通知规则编辑"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationRuleDelete, "审批通知规则删除"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationTaskQuery, "审批通知任务查询"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationTaskSend, "审批通知任务发送"),
        new("Workflow", SharedPermissionCodes.WorkflowNotificationLogQuery, "审批通知日志查询"),

        new("AiCenter", SharedPermissionCodes.AiToolView, "AI 工具查看"),
        new("AiCenter", SharedPermissionCodes.AiWorkbenchView, "AI 工作台查看"),
        new("AiCenter", SharedPermissionCodes.AiSettingsView, "AI 设置查看"),
        new("AiCenter", SharedPermissionCodes.AiSettingsEdit, "AI 设置编辑"),
        new("AiCenter", SharedPermissionCodes.AiChatView, "AI 会话查看"),
        new("AiCenter", SharedPermissionCodes.AiChatCreate, "AI 会话创建"),
        new("AiCenter", SharedPermissionCodes.AiChatDelete, "AI 会话删除"),
        new("AiCenter", SharedPermissionCodes.AiChatArchive, "AI 会话归档"),
        new("AiCenter", SharedPermissionCodes.AiChatCompress, "AI 会话压缩"),
        new("AiCenter", SharedPermissionCodes.AiModelView, "AI 模型查看"),
        new("AiCenter", SharedPermissionCodes.AiModelAdd, "AI 模型新增"),
        new("AiCenter", SharedPermissionCodes.AiModelEdit, "AI 模型编辑"),
        new("AiCenter", SharedPermissionCodes.AiModelDelete, "AI 模型删除"),
        new("AiCenter", SharedPermissionCodes.AiModelDisable, "AI 模型启停"),
        new("AiCenter", SharedPermissionCodes.AiModelTest, "AI 模型测试"),
        new("AiCenter", SharedPermissionCodes.AiModelCopy, "AI 模型复制"),
        new("AiCenter", SharedPermissionCodes.AiProviderView, "AI 供应商查看"),
        new("AiCenter", SharedPermissionCodes.AiProviderAdd, "AI 供应商新增"),
        new("AiCenter", SharedPermissionCodes.AiProviderEdit, "AI 供应商编辑"),
        new("AiCenter", SharedPermissionCodes.AiProviderDelete, "AI 供应商删除"),
        new("AiCenter", SharedPermissionCodes.AiProviderDisable, "AI 供应商启停"),
        new("AiCenter", SharedPermissionCodes.AiProviderTest, "AI 供应商测试"),
        new("AiCenter", SharedPermissionCodes.AiCapabilityView, "AI 能力中心查看"),
        new("AiCenter", SharedPermissionCodes.AiToolConfirmHighRisk, "AI 高风险工具确认"),
        new("AiCenter", SharedPermissionCodes.AiToolDataCenterView, "数据中心 AI 工具查看"),
        new("AiCenter", SharedPermissionCodes.AiToolDataCenterRead, "数据中心 AI 工具读取"),
        new("AiCenter", SharedPermissionCodes.AiToolDataCenterWrite, "数据中心 AI 工具写入"),
        new("AiCenter", SharedPermissionCodes.AiToolDataCenterOperate, "数据中心 AI 工具操作"),

        new("SystemAdministration", SharedPermissionCodes.SystemUserQuery, "用户管理查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemUserAdd, "用户管理新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemUserEdit, "用户管理编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemUserDelete, "用户管理删除"),
        new("SystemAdministration", SharedPermissionCodes.SystemUserGrantRole, "用户分配角色"),
        new("SystemAdministration", SharedPermissionCodes.SystemUserResetPassword, "用户重置密码"),

        new("SystemAdministration", SharedPermissionCodes.SystemDeptQuery, "部门管理查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemDeptAdd, "部门管理新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemDeptEdit, "部门管理编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemDeptDelete, "部门管理删除"),

        new("SystemAdministration", SharedPermissionCodes.SystemPositionQuery, "岗位管理查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemPositionAdd, "岗位管理新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemPositionEdit, "岗位管理编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemPositionDelete, "岗位管理删除"),

        new("SystemAdministration", SharedPermissionCodes.SystemMenuQuery, "菜单管理查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemMenuAdd, "菜单管理新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemMenuEdit, "菜单管理编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemMenuDelete, "菜单管理删除"),

        new("SystemAdministration", SharedPermissionCodes.SystemRoleQuery, "角色管理查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemRoleAdd, "角色管理新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemRoleEdit, "角色管理编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemRoleDelete, "角色管理删除"),
        new("SystemAdministration", SharedPermissionCodes.SystemRoleGrant, "角色授权"),

        new("SystemAdministration", SharedPermissionCodes.SystemDictQuery, "字典管理查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemDictAdd, "字典管理新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemDictEdit, "字典管理编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemDictDelete, "字典管理删除"),

        new("SystemAdministration", SharedPermissionCodes.SystemParameterQuery, "系统参数查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemParameterAdd, "系统参数新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemParameterEdit, "系统参数编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemParameterDelete, "系统参数删除"),

        new("SystemAdministration", SharedPermissionCodes.SystemAnnouncementQuery, "通知公告查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemAnnouncementAdd, "通知公告新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemAnnouncementEdit, "通知公告编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemAnnouncementDelete, "通知公告删除"),
        new("SystemAdministration", SharedPermissionCodes.SystemAnnouncementPublish, "通知公告发布"),
        new("SystemAdministration", SharedPermissionCodes.SystemAnnouncementWithdraw, "通知公告撤回"),
        new("SystemAdministration", SharedPermissionCodes.SystemAnnouncementTop, "通知公告置顶"),

        new("SystemAdministration", SharedPermissionCodes.SystemOperationLogQuery, "操作日志查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemLoginLogQuery, "登录日志查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemOnlineUserQuery, "在线用户查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemOnlineUserKick, "在线用户下线"),

        new("SystemAdministration", SharedPermissionCodes.SystemScheduledJobQuery, "任务调度查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemScheduledJobAdd, "任务调度新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemScheduledJobEdit, "任务调度编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemScheduledJobDelete, "任务调度删除"),
        new("SystemAdministration", SharedPermissionCodes.SystemScheduledJobTrigger, "任务调度执行"),
        new("SystemAdministration", SharedPermissionCodes.SystemScheduledJobLog, "任务调度日志"),

        new("SystemAdministration", SharedPermissionCodes.SystemAbpSettingQuery, "ABP 基础设施查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemAbpSettingEdit, "ABP 基础设施编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemAbpSettingTest, "ABP 基础设施测试"),

        new("SystemAdministration", SharedPermissionCodes.SystemFileQuery, "文件中心查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemFileUpload, "文件上传"),
        new("SystemAdministration", SharedPermissionCodes.SystemFilePreview, "文件预览"),
        new("SystemAdministration", SharedPermissionCodes.SystemFileDownload, "文件下载"),
        new("SystemAdministration", SharedPermissionCodes.SystemFileDelete, "文件删除"),

        new("SystemAdministration", SharedPermissionCodes.SystemPrintQuery, "打印中心查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemPrintAdd, "打印模板新增"),
        new("SystemAdministration", SharedPermissionCodes.SystemPrintEdit, "打印模板编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemPrintDelete, "打印模板删除"),
        new("SystemAdministration", SharedPermissionCodes.SystemPrintPublish, "打印模板发布"),
        new("SystemAdministration", SharedPermissionCodes.SystemPrintUse, "打印模板使用"),
        new("SystemAdministration", SharedPermissionCodes.SystemPrintDefault, "设置默认打印模板"),

        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewResource, "查询视图资源"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewQuery, "查询视图查询"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewEdit, "查询视图编辑"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewDesign, "查询视图设计"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewPreview, "查询视图预览"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewPublish, "查询视图发布"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewRollback, "查询视图回滚"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewExport, "查询视图导出"),
        new("SystemAdministration", SharedPermissionCodes.SystemQueryViewTask, "查询视图任务")
    ];

    public static readonly IReadOnlyList<string> PermissionCodes =
        Definitions.Select(item => item.PermissionCode)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

    public static readonly IReadOnlyList<string> ConsolePermissionCodes =
        SharedPermissionCodes.AppConsolePermissionCodes;

    public static readonly IReadOnlyList<string> FixedMenuPermissionCodes =
        PermissionCodes;
}
