namespace AsterERP.Api.Application.ApplicationDataCenter.SqlScripts;

public sealed record ApplicationDataCenterSqlScriptBareIdentifierExpression(string Identifier) : ApplicationDataCenterSqlScriptExpression;
